### ISSUE TITLE
Productize app tokens for service integration

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#10292]
We have an initial implementation for app tokens, but it is disabled by default and marked as experimental.

App tokens are intended to be generated by end users so they can integrate legacy tools that do not support OIDC. However, the current implementation cannot scope the token which is one of the reasons why we marked this as experimental.

There is another use case that we can productize already. The admin can generate app tokens for system accounts used by external services that can then interact with the graph api, e.g. to manage space membership.

The latter does not need to expose the token generation endpoint, as only admins can generate tokens. A PR for the helm chart that adds this as a feature is in https://github.com/owncloud/ocis-charts/pull/767

**Comment by butonic** [comment]
cc @tbsbdr @dragotin @micbar @wkloucek

The code to support this scope / use case is implemented and [documented](https://owncloud.dev/services/auth-app/) but needs a security review.

**Comment by tbsbdr** [comment]
@micbar @dragotin I consider app tokens to be extremely important. I propose to scope app tokens for the next qa-sprint (from what w know as of today: do we still need development or solely security-qa?) do you agree to scope app tokens in the next sprint?

**Comment by micbar** [comment]
- [ ] Needs a security review.

**Comment by micbar** [comment]
# Security Code Review

## Tasks

- [ ] Do a code review on ocis and reva code checking for obviuos issues
- [ ] Check that the config switch to "allow impersonation" is correctly implemented and cannot be abused
- [ ] Check the the tokens are not usable to access data of other users

@kobergj @DeepDiver1975  Please add more if needed.

**Comment by micbar** [comment]
Needs more info before closing.

**Comment by 2403905** [comment]
Checklist:
- [x] Checked the CLI 
- [x] Checked if the impersonation API works only when  the `AUTH_APP_ENABLE_IMPERSONATION=true`
- [x] Checked if only users with `admin` rights can issue a key via the impersonation API.
- [x] Checked if the token expiration works properly.
- [x] Checked if access was denied to another user's personal space and that wasn't shared with the key owner.

**Comment by micbar** [comment]
@mmattel Fine from ENG POV, could you check if the dev docs are sufficient?
