### ISSUE TITLE
List of release blockers from devops team side

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#10344]
Collecting issues which blocked release 7.0.0 from devops team side: 

- [x] https://github.com/owncloud/ocis/issues/10381 
  - PR in https://github.com/owncloud/ocis/pull/10405
- [ ] https://github.com/owncloud/enterprise/issues/6917
- [x] https://github.com/owncloud/enterprise/issues/6915
- [x] https://github.com/owncloud/web-extensions/issues/40 / https://kiteworks.atlassian.net/browse/OCSRE-374 (German translations were added manually, available via `unzip-v0.3.0`)
- [x] https://github.com/owncloud/enterprise/issues/6918
- [x] https://github.com/owncloud/enterprise/issues/6929
- [x] https://github.com/owncloud/enterprise/issues/6907  - > this is NOT a blocker
- [x] https://github.com/owncloud/ocis/issues/10306 -> template usage with a office that is not called "Collabora" or "OnlyOffice", but eg. `Foo-Office`
- [x] https://github.com/owncloud/ocis/issues/10479 -> config issue, ocis charts issue https://github.com/owncloud/ocis-charts/issues/790
- [x] https://github.com/owncloud/enterprise/issues/6966 --> Low success rate while uploading files
- [x] https://github.com/owncloud/enterprise/issues/6984

New finding:
- [x] https://github.com/owncloud/enterprise/issues/6974
- [x] https://github.com/owncloud/enterprise/issues/6987

CC @dj4oC

**Comment by kobergj** [comment]
@micbar @dragotin can you answer
> If OCM is really a thing

?

**Comment by kwdrago** [comment]
yes, of course it is "a thing", we are working on the issues mentioned above.

**Comment by micbar** [comment]
The last open item is the load test.

**Comment by dj4oC** [comment]
https://github.com/owncloud/enterprise/issues/6966 added to the list

**Comment by wkloucek** [comment]
https://github.com/owncloud/enterprise/issues/6967 added to the list

**Comment by dj4oC** [comment]
https://github.com/owncloud/enterprise/issues/6974 added to the list

**Comment by wkloucek** [comment]
@dj4oc @d7oc @micbar I'd prefer to remove OCM from the release blockers list. What we plan in https://kiteworks.atlassian.net/browse/OCSRE-375?focusedCommentId=1745490 (and following) can also be achieved with a oCIS DEV / rolling version.

I'd find it more important to have a oCIS release soon than it including some state of OCM that still may not be sufficient

**Comment by d7oc** [comment]
I though we exactly stated that already in the call on Tuesday...

**Comment by wkloucek** [comment]
I removed the whole OCM block from the blockers (see commments above):

> If OCM is really a thing:
> - [ ] https://github.com/owncloud/enterprise/issues/6967
> - [x] https://github.com/owncloud/ocis/issues/10355
> - [x] https://github.com/owncloud/ocis/issues/10358
> - [x] https://github.com/owncloud/ocis/issues/10272

**Comment by wkloucek** [comment]
I added https://github.com/owncloud/enterprise/issues/6984

**Comment by dj4oC** [comment]
added: https://github.com/owncloud/enterprise/issues/6987

**Comment by wkloucek** [comment]
There can not be any more blockers for the 7.0.0 release, because it has been released https://github.com/owncloud/ocis/releases/tag/v7.0.0
