### ISSUE TITLE
Update Tracker Template

### ISSUE THREAD

**Issue by refs** [owncloud/ocis#105]
# Extensions Update Tracker

[UPDATE DESCRIPTION]

## How to use this template

Copy the below dependency tree -> find the node that changes -> get rid of everything else.

### example

We want to pull the latest `phoenix` release and add it to `ocis`

1. [go to the template](#template)
2. find the phoenix node on the list
3. copy all parent nodes up to the root (ocis)
4. get rid of everything else
5. your list should look like this:

```
- [ ] [ocis](https://githug.com/owncloud/ocis)
    - [ ] [ocis-phoenix](https://github.com/owncloud/ocis-phoenix)
      - [ ] [phoenix](https://github.com/owncloud/phoenix)
```

# template

```
- [ ] [ocis](https://github.com/owncloud/ocis)
    - [ ] [ocis-hello](https://github.com/owncloud/ocis-hello)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
    - [ ] [ocis-konnectd](https://github.com/owncloud/ocis-konnectd)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
    - [ ] [ocis-graph](https://github.com/owncloud/ocis-graph)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
    - [ ] [ocis-reva](https://github.com/owncloud/ocis-reva)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
      - [ ] [reva](https://github.com/cs3org/reva/)
    - [ ] [ocis-bridge](https://github.com/owncloud/ocis-bridge)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
    - [ ] [ocis-accounts](https://github.com/owncloud/ocis-accounts)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
    - [ ] [ocis-cli](https://github.com/owncloud/ocis-cli)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
    - [ ] [ocis-ocs](https://github.com/owncloud/ocis-ocs)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
    - [ ] [ocis-devldap](https://github.com/owncloud/ocis-devldap)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
    - [ ] [ocis-webdav](https://github.com/owncloud/ocis-webdav)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
    - [ ] [ocis-phoenix](https://github.com/owncloud/ocis-phoenix)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
      - [ ] [phoenix](https://github.com/owncloud/phoenix)
    - [ ] [ocis-graph-explorer](https://github.com/owncloud/ocis-graph-explorer)
      - [ ] [ocis-pkg](https://github.com/owncloud/ocis-pkg)
      - [ ] [graph-explorer](https://github.com/owncloud/graph-explorer)
```
