### ISSUE TITLE
Ability to return error messages in Webdav response bodies

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1293]
In OC 10, the response body for errors/exceptions in Webdav would contain an XML body generated by Sabre DAV. In OCIS the body is empty in such cases.

Example Sabre response:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No public access to this resource., Username or password was incorrect, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, Username or password was incorrect</s:message>
</d:error>
```

TODOs:

- [ ] check whether clients are already parsing exception messages from bodies
- [ ] discuss how to return such messages in OCIS

Related tickets:

- [ ] [MKCOL on existing resource](https://github.com/owncloud/ocis-reva/issues/168)
- [ ] [PROPFIND on non-existing resource](https://github.com/owncloud/ocis-reva/issues/163)
- [ ] [HTTP 401 Unauthorized responses don't contain a body](https://github.com/owncloud/ocis-reva/issues/30)

As discussed with @butonic we might still want a mechanism for returning more information about the error, but it's currently unclear what the format would be.

**Comment by refs** [comment]
we did introduce a package for this on Reva; we need to revamp this issue.

**Comment by individual-it** [comment]
I've tried to access webdav with other tools like the file-manager and LibreOffice and they don't ask for a username/password. I believe this issue could be the reason.

**Comment by fschade** [comment]
Please open again if the ticket is still relevant

**Comment by DeepDiver1975** [comment]
🤖 Automated issue triage by the Claude Code review agent.

This issue requested the ability to return error messages in WebDAV response bodies, ideally in the existing Sabre-compatible format so that the desktop and iOS clients (which parse `d:error` → `s:exception` / `s:message`) keep working, with room to add error codes later.

That capability is now implemented in the reva WebDAV (`ocdav`) service that oCIS uses. See [`internal/http/services/owncloud/ocdav/error.go`](https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocdav/error.go):

- Error responses are serialized and written to the WebDAV response body via an `errorXML` struct that emits exactly `<d:error>` with `<s:exception>` and `<s:message>` — the same Sabre namespace/format agreed on in this thread for client compatibility.
- The Sabre exception types the iOS SDK keys off (`NotFound`, `PreconditionFailed`, `PermissionDenied`, `NotAuthenticated`, `Conflict`, `BadRequest`, `MethodNotAllowed`) are mapped to the appropriate HTTP status codes.
- The future evolution discussed here — error codes — is also present: the struct carries an `s:errorcode` element (plus an `s:header` extension for the conflicting request header).

Since the requested functionality exists in current oCIS/reva, we are closing this as resolved.

If you observe a specific WebDAV error case where the body is missing, malformed, or breaks a client (e.g. the earlier report about file-manager/LibreOffice not prompting for credentials), that is a concrete bug — please **reopen** or file a fresh issue with the exact request/response so it can be tracked precisely. Thank you\!
