### ISSUE TITLE
ocis 1.1.0

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#1365]
# Release 1.1.0 Tech Preview

Engineering Driven hardening and patch release. Minor version change is neede due to config changes. Pre 1.1.0 deployments will not break, but 1.1.0 deployment best practises will not be backwards compatible.

## Changelog

* Change - Disable pretty logging by default: [#1133](https://github.com/owncloud/ocis/pull/1133)
* Change - Add "volume" declaration to docker images: [#1375](https://github.com/owncloud/ocis/pull/1375)
* Change - Add "expose" information to docker images: [#1366](https://github.com/owncloud/ocis/pull/1366)
* Change - Generate cryptographically secure state token: [#1203](https://github.com/owncloud/ocis/pull/1203)
* Change - Move k6 to cdperf: [#1358](https://github.com/owncloud/ocis/pull/1358)
* Change - Update go version: [#1364](https://github.com/owncloud/ocis/pull/1364)
* Change - Update ownCloud Web to v1.0.1: [#1191](https://github.com/owncloud/ocis/pull/1191)
* Enhancement - Add OCIS_URL env var: [#1148](https://github.com/owncloud/ocis/pull/1148)
* Enhancement - Use sync.cache for roles cache: [#1367](https://github.com/owncloud/ocis/pull/1367)
* Enhancement - Add named locks and refactor cache: [#1212](https://github.com/owncloud/ocis/pull/1212)
* Enhancement - Update reva to v1.5.1: [#1372](https://github.com/owncloud/ocis/pull/1372)
* Enhancement - Update reva to v1.4.1-0.20210111080247-f2b63bfd6825: [#1194](https://github.com/owncloud/ocis/pull/1194)

## Tasks
- [x] Brief marketing heads up @pmaier1 
- [x] Update reva to v1.5.1 @IljaN 
- [x] Update web to v1.0.1 
- [x] Preliminary Changelog @micbar https://github.com/owncloud/ocis/blob/c2f154f7cd6db276928dc51c10c5eaf0c8e3a8ad/CHANGELOG.md
- [x] Release Notes @pmaier1 
- [x] Create branch `release-1.1.0` -> CODEFREEZE @fschade 
- [x] Prepare Changelog @kulmann 
- [x] Create pre release tag `v1.1.0-rc1` @kulmann 
- [x] Smoke Test @kulmann @fschade @dragotin 
- [x] run K6 on the tag @fschade 
- [ ] ~~If needed, fix issues or write down known issues~~
- [x] Create final signed tag `v1.1.0` @kulmann 
- [x] Merge release notes https://github.com/owncloud/ocis/pull/1484 @kulmann 
- [x] Ping marketing to update all download links @kulmann 
- [ ] Merge back release branch @fschade @kulmann

**Comment by kulmann** [comment]
@pmaier1 you can find the changelog for the release notes in the `unreleased` section at the top of this file: https://github.com/owncloud/ocis/blob/c2f154f7cd6db276928dc51c10c5eaf0c8e3a8ad/CHANGELOG.md

**Comment by fschade** [comment]
# K6 results on intel test machine

## ocis
creating users with basic auth fails
https://gist.github.com/fschade/c558fd952fdc1322ac54321c181a6947

## oc10
TBD

**Comment by fschade** [comment]
# Smoke testing

## Files
- [X] as einstein - upload 1930 files
- [X] as einstein - share the folder to admin as viewer
- [X] as admin - accept share
- [X] as admin - try do delete file from shared folder
  - I can see the delete button but server doesn't allow it
- [X] as admin - try to add file
- [X] as admin - copy 1400 files from share to home
  - no visual copy feedback
- [X] as einstein - add new file to share
- [X] as admin - receive new file in existing share
- [X] as einstein - unshare folder from shared with others 
- [X] as admin - try to revisit old share
- [X] as einstein - share folder with admin as editor
- [X] as admin - rename file
- [X] as admin - add file
- [X] as admin - delete file

## Settings
- [X] change language

## Accounts
- [X] as admin - create account
- [X] as new account - login
- [X] as admin - block new account
- [X] as new account - reload, expected auto logout
- [X] as admin - re-activate new account
- [X] as new account - re-login, expected session still active
- [X] as admin - delete new account

**Comment by kulmann** [comment]
# Smoke testing on https://localhost:9200/

- ✔️ login as einstein
- ✔️ create a folder "eBooks"
- ✔️ share "eBooks" with marie as viewer
- ✔️share "eBooks" with richard as editor
- ✔️ create a subfolder "eBooks/test"
- ✔️ upload "paper.pdf" into "eBooks/test"
- ✔️ upload "image.jpg" into "/"
- ✔️ copy "image.jpg" into "eBooks"
- ✔️ move "image.jpg" into "eBooks/test"
- ✔️ share "eBooks" as unprotected public link with viewer role
  - ✔️ access unprotected public link
  - ✔️ no write actions available on files, folders, subfolders, files in subfolders
  - ✔️ download of files works
  - ❌ viewing images in mediaviewer doesn't work - known issue (add link)
- ✔️ share "eBooks" as password protected public link with editor role
  - ✔️ access password protected public link
  - ✔️ write actions available on files, folders, subfolders, files in subfolders
  - ✔️ deleting files and folders works and is visible to share owner
  - ✔️ renaming files and folders works and is visible to share owner
  - ✔️ uploading files works and is visible to share owner
  - ✔️ download of files works
  - ❌ viewing images in mediaviewer doesn't work - known issue (add link)
- ✔️ login as richard
  - ✔️ accept share
  - ✔️ browse into Shares folder


(to be continued)

**Comment by dragotin** [comment]
Smoke test on raspberry-pi with ARM build and basic remote setup also successful.

**Comment by fschade** [comment]
@pmaier1, can you please have a look

---
## ownCloud Infinite Scale 1.1.0 Technology Preview
We are pleased to announce the availability of ownCloud Infinite Scale 1.1.0 Technology Preview, the new Infinite Scale platform.

### Improvements in 1.1.0 Technology Preview
- Performance and stability improvements for installations with multiple concurrent users
- Simplify configuration by introducing a new environment variable OCIS_URL
- Beta release of [ownCloud performance measurement scripts](https://github.com/owncloud/cdperf)
- Update ownCloud web to [v1.0.1](https://github.com/owncloud/web/releases/tag/v1.0.1)
- Update reva to [v1.5.1](https://github.com/cs3org/reva/releases/tag/v1.5.1)
