### ISSUE TITLE
Release 1.2.0 Tech Preview

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#1654]
## Tasks
- [ ] Brief marketing heads up @pmaier1 
- [ ] Update reva to 
- [ ] Update web to 
- [ ] Preliminary Changelog @micbar 
- [ ] Release Notes @pmaier1 
- [ ] Create branch `release-1.2.0` -> CODEFREEZE
- [ ] Prepare Changelog
- [ ] Create pre release tag `v1.2.0-rc1`
- [ ] Smoke Test 
- [ ] run K6 on the tag 
- [ ] ~~If needed, fix issues or write down known issues~~
- [ ] Create final signed tag `v1.2.0`
- [ ] Merge release notes https://github.com/owncloud/ocis/pull/1484
- [ ] Ping marketing to update all download links 
- [ ] Merge back release branch

**Comment by wkloucek** [comment]
We need to add a migration notice described in #1569  to the change log.

@butonic you mentioned another breaking change regarding the shares.json? Currently the only way to go forward is deleting that file?

**Comment by butonic** [comment]
yes, @ishank011 will add an updated changelog with https://github.com/owncloud/ocis/pull/1626#pullrequestreview-591076607

**Comment by ishank011** [comment]
@butonic I added the changelog. It's good to be merged

**Comment by kulmann** [comment]
Examples for smoke testing steps are:
- https://github.com/owncloud/ocis/issues/1365#issuecomment-765512301 and
- https://github.com/owncloud/ocis/issues/1365#issuecomment-765531566

There was also some smoke testing on an RPi.

**Comment by butonic** [comment]
@ishank011 we'll do another smoke test before merging

**Comment by kulmann** [comment]
# Smoke testing on https://localhost:9200/ on macOS

## Files
- ✔️ login as einstein
- ✔️ create a folder "eBooks"
- ✔️ share "eBooks" with marie as viewer
- ✔️share "eBooks" with richard as editor
- ✔️ create a subfolder "eBooks/test"
- ✔️ upload "paper.pdf" into "eBooks/test"
- ✔️ upload "image.jpg" into "/"
- ✔️ copy "image.jpg" into "eBooks"
- ✔️ move "image.jpg" into "eBooks/test"
- ✔️ share "eBooks" as unprotected public link with viewer role
  - ✔️ access unprotected public link
  - ✔️ no write actions available on files, folders, subfolders, files in subfolders
  - ✔️ download of files works (doublecheck in OS filebrowser)
  - ❌ viewing images in mediaviewer doesn't work - [known issue #1075](https://github.com/owncloud/ocis/issues/1075)
- ✔️ share "eBooks" as password protected public link with editor role
  - ✔️ access password protected public link
  - ✔️ write actions available on files, folders, subfolders, files in subfolders
  - ✔️ deleting files and folders works and is visible to share owner
  - ✔️ renaming files and folders works and is visible to share owner
  - ✔️ uploading files works and is visible to share owner
  - ✔️ download of files works (doublecheck in OS filebrowser)
  - ❌ viewing images in mediaviewer doesn't work - [known issue #1075](https://github.com/owncloud/ocis/issues/1075)
- ❌ restoring a file from the trahsbin that was deleted from within a public link fails
- ✔️ permanently deleting a file from the trashbin works
- ✔️ clearing the trashbin works
- ✔️ login as richard
  - ✔️ accept "eBooks" share
  - ✔️ browse into "eBooks" share by clicking on it in "Shared with me"
  - ✔️ see breadcrumbs as "/Shares/eBooks"
  - ✔️ browse into "test" subfolder
  - ✔️ open "image.jpg" in mediaviewer
  - ✔️ close mediaviewer, land in "/Shares/eBooks/test" in the files app again
  - ✔️ open right sidebar (details) for "image.jpg"
  - ✔️ rename "image.jpg" to "renamed-by-richard.jpg"
  - ✔️ download of "renamed-by-richard.jpg" works (doublecheck in OS filebrowser)
  - ✔️ re-upload "renamed-by-richard.jpg", creating a new version
  - ❌ download older version of "renamed-by-richard.jpg" fails (501 - not implemented)
  - ❌ restoring older version creates a new version - [known issue #1214](https://github.com/owncloud/ocis/issues/1214)
- ✔️ login as marie
  - ✔️ accept "eBooks" share
  - ✔️ browse into "eBooks" share by going to "All files" and browsing into "/Shares/eBooks"
  - ✔️ browse into "test" subfolder
  - ✔️ open "renamed-by-richard.jpg" in mediaviewer
  - ✔️ close mediaviewer, land in "/Shares/eBooks/test" in the files app again
  - ✔️ open right sidebar (details) for "renamed-by-richard.jpg"
  - ✔️ action "Rename" is not available in the right sidebar
  - ✔️ action "Move" is not available in the right sidebar
  - ✔️ action "Delete" is not available in the right sidebar
  - ✔️ check the checkbox for "renamed-by-richard.jpg" in the files list
  - ✔️ action "Move" is not available in the batch actions at the top
  - ❌ action "Delete" is available in the batch actions at the top


## Settings
- ✔️ login as marie
- ✔️ go to settings page by clicking on username (top right) and clicking on "Settings"
- ✔️ select "Deutsch" as language
- ✔️ nav items in the left sidebar are displayed in german language
- ✔️ browse to files app
- ✔️ nav items in the left sidebar are displayed in german language
- ✔️ table header and footer of the "All files" list are displayed in german language
- ✔️ button and sub-actions for creating new resources is displayed in german language
- ✔️ logout and then login as richard
- ✔️ all UI elements mentioned before are again displayed in english language (as language for richard was not changed)

**Comment by micbar** [comment]
@pmaier1, can you please have a look

---
## ownCloud Infinite Scale 1.2.0 Technology Preview
We are pleased to announce the availability of ownCloud Infinite Scale 1.2.0 Technology Preview, the new Infinite Scale platform.

### Improvements in 1.120 Technology Preview
- Update ownCloud web to [v2.0.0](https://github.com/owncloud/web/releases/tag/v2.0.0)
- Update reva to [v1.6.0](https://github.com/cs3org/reva/releases/tag/v1.6.0)
- Reduced the bundle size in onwCloud Web
- Accessibility - Make use of new design-system oc-table: #1597
- Bugfix - Fix etcd address configuration: [#1546](https://github.com/owncloud/ocis/pull/1546)
* Bugfix - Remove unimplemented config file option for oCIS root command: [#1636](https://github.com/owncloud/ocis/pull/1636)
* Bugfix - Fix thumbnail generation when using different idp: [#1624](https://github.com/owncloud/ocis/issues/1624)
* Change - Initial release of graph and graph explorer: [#1594](https://github.com/owncloud/ocis/pull/1594)
* Change - Update ownCloud Web to v2.0.0: [#1661](https://github.com/owncloud/ocis/pull/1661)
* Enhancement - Make use of new design-system oc-table: [#1597](https://github.com/owncloud/ocis/pull/1597)
* Enhancement - Use a default protocol parameter instead of explicitly disabling tus: [#1331](https://github.com/cs3org/reva/pull/1331)
* Enhancement - Functionality to map home directory to different storage providers: [#1186](https://github.com/owncloud/ocis/pull/1186)
 * Fix https://github.com/cs3org/reva/issues/1461: Fix public link webdav permissions
 * Fix https://github.com/cs3org/reva/issues/1429: Purge non-empty dirs from trash-bin
 * Fix https://github.com/cs3org/reva/issues/1408: Get error status from trash-bin response
 * Enh https://github.com/cs3org/reva/issues/1400: Checksum support
 * Enh https://github.com/cs3org/reva/issues/1453: Add functionality to share resources with groups
 * Enh https://github.com/cs3org/reva/issues/1462: Hash public share passwords
 * Enh https://github.com/cs3org/reva/issues/1429: Add s3ng storage driver, storing blobs in a s3-compatible blobstore

**Comment by labkode** [comment]
@micbar typo
Reduced the bundle size in onwCloud Web =>
Reduced the bundle size in ownCloud Web

**Comment by dragotin** [comment]
Completed successfully :-)
