### ISSUE TITLE
Ocis 1.0.0-beta2

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#174]
# Tasks
- [x] ocis-pkg needs to be released, `v2.2.0`

## Proxy
- [x] Release v0.3.0
- [x] Update ocis-pkg https://github.com/owncloud/ocis-proxy/pull/30
- [x] Release v0.3.1

## ocis-webdav
- [x] Update ocis-pkg https://github.com/owncloud/ocis-webdav/pull/17
- [x] Release v0.1.0 [ocis-webdav/v0.1.0](https://github.com/owncloud/ocis-webdav/releases/tag/v0.1.0)

## Phoenix
- [x] Release v0.7.0
- [x] Update in ocis-phoenix
- [x] Release ocis-phoenix v0.4.0
- [x] Release ocis-phoenix v0.4.1 to fix the assets in v0.4.0

## Thubmbnails
- [x] Release v0.1.0 [ocis-thumbnails/v0.1.0](https://github.com/owncloud/ocis-thumbnails/releases/tag/v0.1.0)

## Reva
- [x] merge https://github.com/owncloud/ocis-reva/pull/125
- [x] Tag ocis-reva v0.1.1

## OCIS
- [x] Update ocis-pkg
- [x] Update ocis-reva
- [x] Update ocis-webdav
- [x] Update ocis-proxy
- [x] Update ocis-phoenix
- [x] Tag oCIS 1.0.0-beta2

**Comment by micbar** [comment]
@butonic Can you clarify the reva parts

**Comment by micbar** [comment]
# OCIS 1.0.0-beta2

## Downloads
- https://download.owncloud.com/ocis/ocis/1.0.0-beta2/

## Docker
`docker pull owncloud/ocis:1.0.0-beta2`
