### ISSUE TITLE
Release 1.3.0 Tech Preview

### ISSUE THREAD

**Issue by fschade** [owncloud/ocis#1775]
## Tasks
- [ ] Brief marketing heads up @pmaier1 
- [x] release [web to 2.0.2](https://github.com/owncloud/web/releases/tag/v2.0.2) @kulmann
- [x] update to [web v2.0.2 in ocis](https://github.com/owncloud/ocis/pull/1776) @pascalwengerter 
- [x] Preliminary Changelog @micbar
- [x] Release Notes @dragotin 
- [x] Create branch `release-1.3.0` -> CODEFREEZE @micbar
- [x] Prepare Changelog @micbar 
- [x] Create pre release tag `v1.3.0-rc1` @micbar
- [x] Smoke Test @kulmann, @pascalwengerter 
- [x] run K6 on the tag @fschade 
- [x] If needed, fix issues or write down known issues @kulmann, @pascalwengerter @fschade 
- [x] Create final signed tag `v1.3.0` @micbar @dragotin 
- [x] Merge release notes @dragotin 
- [x] Check successful CI run https://drone.owncloud.com/owncloud/ocis/4037
- [x] Ping marketing to update all download links @dragotin 
- [x] Merge back release branch @kulmann @micbar https://github.com/owncloud/ocis/pull/1788

## Preliminary Changelog

ocis 1.3.0 Tech Preview is a bugfix and maintenance release.

### mentionable items in reva:
- Fix #1425: Align href URL encoding with oc10
- Fix #1461: Fix public link webdav permissions
- Fix #1429: Purge non-empty dirs from trash-bin
- Enh #1400: Checksum support
- Enh #1477: Set quota when creating home directory in EOS
- Enh #1453: Add functionality to share resources with groups
- Enh #1429: Add s3ng storage driver, storing blobs in a s3-compatible blobstore

### mentionable in oCIS

* Change - Update ownCloud Web to v2.0.2: [#1776](https://github.com/owncloud/ocis/pull/1776)
* Enhancement - Update go-micro to v3.5.1-0.20210217182006-0f0ace1a44a9: [#1670](https://github.com/owncloud/ocis/pull/1670)
* Enhancement - Update reva to v1.6.1-0.20210223065028-53f39499762e: [#1683](https://github.com/owncloud/ocis/pull/1683)
* Enhancement - Add initial nats and kubernetes registry support: [#1697](https://github.com/owncloud/ocis/pull/1697)

Details

**Comment by fschade** [comment]
# K6 results on intel test machine

## ocis (1.3.0)
shell```
```

## ocis (1.1.0)
https://github.com/owncloud/ocis/issues/1365#issuecomment-765391977

**Comment by micbar** [comment]
# Changelog for [1.3.0] (2021-03-09)

The following sections list the changes for 1.3.0.

[1.3.0]: https://github.com/owncloud/ocis/compare/v1.2.0...v1.3.0

## Summary

* Bugfix - Purposely delay accounts service startup: [#1734](https://github.com/owncloud/ocis/pull/1734)
* Bugfix - Add missing gateway config: [#1716](https://github.com/owncloud/ocis/pull/1716)
* Bugfix - Fix accounts initialization: [#1696](https://github.com/owncloud/ocis/pull/1696)
* Bugfix - Fix the ttl of the authentication middleware cache: [#1699](https://github.com/owncloud/ocis/pull/1699)
* Change - Update ownCloud Web to v2.0.1: [#1683](https://github.com/owncloud/ocis/pull/1683)
* Change - Update ownCloud Web to v2.0.2: [#1776](https://github.com/owncloud/ocis/pull/1776)
* Enhancement - Remove the JWT from the log: [#1758](https://github.com/owncloud/ocis/pull/1758)
* Enhancement - Update go-micro to v3.5.1-0.20210217182006-0f0ace1a44a9: [#1670](https://github.com/owncloud/ocis/pull/1670)
* Enhancement - Update reva to v1.6.1-0.20210223065028-53f39499762e: [#1683](https://github.com/owncloud/ocis/pull/1683)
* Enhancement - Add initial nats and kubernetes registry support: [#1697](https://github.com/owncloud/ocis/pull/1697)

## Details

* Bugfix - Purposely delay accounts service startup: [#1734](https://github.com/owncloud/ocis/pull/1734)

   As it turns out the race condition between `accounts <-> storage-metadata` still remains.
   This PR is a hotfix, and it should be followed up with a proper fix. Either:

   - block the accounts' initialization until the storage metadata is ready (using the registry)
   or - allow the accounts service to initialize and use a message broker to signal the accounts the
   metadata storage is ready to receive requests.

   https://github.com/owncloud/ocis/pull/1734

* Bugfix - Add missing gateway config: [#1716](https://github.com/owncloud/ocis/pull/1716)

   The auth provider `ldap` and `oidc` drivers now need to be able talk to the reva gateway. We added
   the `gatewayscv` to the config that is passed to reva.

   https://github.com/owncloud/ocis/pull/1716

* Bugfix - Fix accounts initialization: [#1696](https://github.com/owncloud/ocis/pull/1696)

   Originally the accounts service relies on both the `settings` and `storage-metadata` to be up
   and running at the moment it starts. This is an antipattern as it will cause the entire service to
   panic if the dependants are not present.

   We inverted this dependency and moved the default initialization data (i.e: creating roles,
   permissions, settings bundles) and instead of notifying the settings service that the
   account has to provide with such options, the settings is instead initialized with the options
   the accounts rely on. Essentially saving bandwith as there is no longer a gRPC call to the
   settings service.

   For the `storage-metadata` a retry mechanism was added that retries by default 20 times to
   fetch the `com.owncloud.storage.metadata` from the service registry every `500`
   miliseconds. If this retry expires the accounts panics, as its dependency on the
   `storage-metadata` service cannot be resolved.

   We also introduced a client wrapper that acts as middleware between a client and a server. For
   more information on how it works further read [here](https://github.com/sony/gobreaker)

   https://github.com/owncloud/ocis/pull/1696

* Bugfix - Fix the ttl of the authentication middleware cache: [#1699](https://github.com/owncloud/ocis/pull/1699)

   The authentication cache ttl was multiplied with `time.Second` multiple times. This
   resulted in a ttl that was not intended.

   https://github.com/owncloud/ocis/pull/1699

* Change - Update ownCloud Web to v2.0.1: [#1683](https://github.com/owncloud/ocis/pull/1683)

   Tags: web

   We updated ownCloud Web to v2.0.1. Please refer to the changelog (linked) for details on the web
   release.

   https://github.com/owncloud/ocis/pull/1683
   https://github.com/owncloud/web/releases/tag/v2.0.1

* Change - Update ownCloud Web to v2.0.2: [#1776](https://github.com/owncloud/ocis/pull/1776)

   Tags: web

   We updated ownCloud Web to v2.0.2. Please refer to the changelog (linked) for details on the web
   release.

   https://github.com/owncloud/ocis/pull/1776
   https://github.com/owncloud/web/releases/tag/v2.0.2

* Enhancement - Remove the JWT from the log: [#1758](https://github.com/owncloud/ocis/pull/1758)

   We were logging the JWT in some places. Secrets should not be exposed in logs so it got removed.

   https://github.com/owncloud/ocis/pull/1758

* Enhancement - Update go-micro to v3.5.1-0.20210217182006-0f0ace1a44a9: [#1670](https://github.com/owncloud/ocis/pull/1670)

   - We updated from go micro v2 (v2.9.1) go-micro v3 (v3.5.1 edge). - oCIS runtime is now aware of
   `MICRO_LOG_LEVEL` and is set to `error` by default. This decision was made because ownCloud,
   as framework builders, want to log everything oCIS related and hide everything unrelated by
   default. It can be re-enabled by setting it to a log level other than `error`. i.e:
   `MICRO_LOG_LEVEL=info`. - Updated `protoc-gen-micro` to the [latest
   version](https://github.com/asim/go-micro/tree/master/cmd/protoc-gen-micro). -
   We're using Prometheus wrappers from go-micro.

   https://github.com/owncloud/ocis/pull/1670
   https://github.com/asim/go-micro/pull/2126

* Enhancement - Update reva to v1.6.1-0.20210223065028-53f39499762e: [#1683](https://github.com/owncloud/ocis/pull/1683)

  * quota querying and tree accounting [cs3org/reva#1405](https://github.com/cs3org/reva/pull/1405)

   https://github.com/owncloud/ocis/pull/1683
   https://github.com/cs3org/reva/pull/1405

* Enhancement - Add initial nats and kubernetes registry support: [#1697](https://github.com/owncloud/ocis/pull/1697)

   We added initial support to use nats and kubernetes as a service registry using
   `MICRO_REGISTRY=nats` and `MICRO_REGISTRY=kubernetes` respectively. Multiple nodes can
   be given with `MICRO_REGISTRY_ADDRESS=1.2.3.4,5.6.7.8,9.10.11.12`.

   https://github.com/owncloud/ocis/pull/1697

**Comment by kulmann** [comment]
# Smoke testing on https://localhost:9200/ on macOS with tag v1.3.0-rc1

## Files
- ✔️ login as einstein
- ✔️ create a folder "eBooks"
- ✔️ share "eBooks" with marie as viewer
- ✔️share "eBooks" with richard as editor
- ✔️ create a subfolder "eBooks/test"
- ✔️ upload "paper.pdf" into "eBooks/test"
- ✔️ upload "image.jpg" into "/"
- ✔️ copy "image.jpg" into "eBooks"
- ✔️ move "image.jpg" into "eBooks/test"
- ✔️ share "eBooks" as unprotected public link with viewer role
  - ✔️ access unprotected public link
  - ✔️ no write actions available on files, folders, subfolders, files in subfolders
  - ✔️ download of files works (doublecheck in OS filebrowser)
  - ❌ viewing images in mediaviewer doesn't work - [known issue #1075](https://github.com/owncloud/ocis/issues/1075)
- ✔️ share "eBooks" as password protected public link with editor role
  - ✔️ access password protected public link
  - ✔️ write actions available on files, folders, subfolders, files in subfolders
  - ✔️ deleting files and folders works and is visible to share owner
  - ✔️ renaming files and folders works and is visible to share owner
  - ✔️ uploading files works and is visible to share owner
  - ✔️ download of files works (doublecheck in OS filebrowser)
  - ❌ viewing images in mediaviewer doesn't work - [known issue #1075](https://github.com/owncloud/ocis/issues/1075)
- ❌ restoring a file from the trahsbin that was deleted from within a public link fails
- ✔️ permanently deleting a file from the trashbin works
- ✔️ clearing the trashbin works
- ✔️ login as richard
  - ✔️ accept "eBooks" share
  - ✔️ browse into "eBooks" share by clicking on it in "Shared with me" 
  - ✔️ see breadcrumbs as "/Shares/eBooks"
  - ✔️ browse into "test" subfolder
  - ✔️ open "image.jpg" in mediaviewer
  - ✔️ close mediaviewer, land in "/Shares/eBooks/test" in the files app again
  - ✔️ open right sidebar (details) for "image.jpg"
  - ✔️ rename "image.jpg" to "renamed-by-richard.jpg"
  - ✔️ download of "renamed-by-richard.jpg" works (doublecheck in OS filebrowser)
  - ✔️ re-upload "renamed-by-richard.jpg", creating a new version
  - ❌ download older version of "renamed-by-richard.jpg" fails (501 - not implemented)
  - ❌ restoring older version creates a new version - [known issue #1214](https://github.com/owncloud/ocis/issues/1214)
- ✔️ login as marie
  - ✔️ accept "eBooks" share
  - ✔️ browse into "eBooks" share by going to "All files" and browsing into "/Shares/eBooks"
  - ✔️ browse into "test" subfolder
  - ✔️ open "renamed-by-richard.jpg" in mediaviewer
  - ✔️ close mediaviewer, land in "/Shares/eBooks/test" in the files app again
  - ✔️ open right sidebar (details) for "renamed-by-richard.jpg"
  - ✔️ action "Rename" is not available in the right sidebar
  - ✔️ action "Move" is not available in the right sidebar
  - ✔️ action "Delete" is not available in the right sidebar
  - ✔️ check the checkbox for "renamed-by-richard.jpg" in the files list
  - ✔️ action "Move" is not available in the batch actions at the top
  - ❌ action "Delete" is available in the batch actions at the top


## Settings
- ✔️ login as marie
- ✔️ go to settings page by clicking on username (top right) and clicking on "Settings"
- ✔️ select "Deutsch" as language
- ✔️ nav items in the left sidebar are displayed in german language
- ✔️ browse to files app
- ✔️ nav items in the left sidebar are displayed in german language
- ✔️ table header and footer of the "All files" list are displayed in german language
- ✔️ button and sub-actions for creating new resources is displayed in german language
- ✔️ logout and then login as richard
- ✔️ all UI elements mentioned before are again displayed in english language (as language for richard was not changed)

**Comment by kulmann** [comment]
Something I found during smoke testing but probably existed before: https://github.com/owncloud/ocis/issues/1787
IMO not a release blocker.
