### ISSUE TITLE
Release 1.4.0 Tech Preview

### ISSUE THREAD

**Issue by fschade** [owncloud/ocis#1866]
## Tasks
- [x] Brief marketing heads up @pmaier1 @dragotin 
- [x] release [web to v2.1.0](https://github.com/owncloud/web/releases/tag/v2.1.0)
- [x] update to web v2.1.0 in ocis @pascalwengerter 
- [x] Update reva to [v1.6.1-0.20210223065028-53f39499762e](https://github.com/owncloud/ocis/pull/1861) in ocis @C0rby 
- [x] Preliminary Changelog @fschade 
- [x] Release Notes @dragotin 
- [x] Create branch `release-1.4.0` -> CODEFREEZE @fschade 
- [x] Prepare Changelog @fschade @dragotin 
- [x] Create pre release tag `v1.4.0-rc1`@fschade 
- [x] Smoke Test @pascalwengerter @fschade 
- [x] run K6 on the tag @fschade 
- [ ] If needed, fix issues or write down known issues
- [x] Create final signed tag `v1.4.0` @fschade 
- [x] Merge release notes @kulmann 
- [x] Check successful CI run on v1.4.0 tag @fschade 
- [x] Ping marketing to update all download links @pmaier1 
- [ ] Merge back release branch @kulmann

**Comment by fschade** [comment]
## Preliminary Changelog

### Ocis 1.4.0
* Enhancement - Add focus to input elements on login page: #1792
* Enhancement - Improve accessibility to input elements on login page: #1794
* Enhancement - Add new build targets: #1824
* Enhancement - Clarify expected failures: #1790
* Enhancement - Replace special character in login page title with a regular minus: #1813
* Enhancement - File Logging: #1816
* Enhancement - Runtime Hostname and Port are now configurable: #1822
* Enhancement - Generate thumbnails for .gif files: #1791
* Enhancement - Tracing Refactor: #1819
* Enhancement - Update reva to v1.6.1-0.20210326165326-e8a00d9b2368: #1683
* Bugfix - Fix thumbnail generation for jpegs: #1490

### Reva v1.6.1-0.20210223065028-53f39499762e
* Enhancement - quota querying and tree accounting https://github.com/cs3org/reva/pull/1405
* Enhancement - Signature authentication for public links https://github.com/cs3org/reva/pull/1590
* Bugfix - Trashbin API parity https://github.com/cs3org/reva/pull/1552
* Bugfix - Fix webdav file versions endpoint bugs https://github.com/cs3org/reva/pull/1526
* Bugfix - Fix etag changing only once a second https://github.com/cs3org/reva/pull/1576

### Web 2.1.0
* Change - New files list: https://github.com/owncloud/web/issues/4627
* Enhancement - A11y improvements for files app bar: https://github.com/owncloud/web/issues/4786
* Enhancement - Implement live region updates on route changes: https://github.com/owncloud/web/issues/4812
* Bugfix - Open mediaviewer for upper case file extensions: https://github.com/owncloud/web/issues/4647
* Bugfix - Only one <main> tag per HTML document: https://github.com/owncloud/web/issues/1652

**Comment by fschade** [comment]
# Smoke test result
## findings
- if i try do delete a file from a shared folder where i'm a viewer, i can see the delete button.
- if i copy file from a share to my home folder i do not get a visual feedback
- if someone shares a folder with me and i accepted this share, then the owner removes me from the shared with list and re add me. I do not have to re accept the share, it's immediately is accepted.

# Plan
## Files
-  :heavy_check_mark: as einstein - upload lib/private from oc10 tar
- :heavy_check_mark: as einstein - share the folder to admin as viewer
- :heavy_check_mark: as admin - accept share
- :heavy_check_mark: as admin - try do delete a file from shared folder
    - I can see the delete button but server doesn't allow it
- :heavy_check_mark: as admin - try to add file
- :heavy_check_mark: as admin - copy all files from share to home
    - no visual copy feedback
- :heavy_check_mark: as einstein - add new file to share
- :heavy_check_mark: as admin - receive new file in existing share
- :heavy_check_mark: as einstein - unshare folder from shared with others
- :heavy_check_mark: as admin - try to revisit old share
- :heavy_check_mark: as einstein - share same old folder with admin as editor
    - I do not have to accept the share again
- :heavy_check_mark: as admin - rename file
- :heavy_check_mark: as admin - add file
- :heavy_check_mark: as admin - delete file

## Settings
- :heavy_check_mark: change language

## Accounts
- :heavy_check_mark: as admin - create account
- :heavy_check_mark: as new account - login
- :heavy_check_mark: as admin - block new account
- :heavy_check_mark: as new account - reload, expected auto logout
- :heavy_check_mark: as admin - re-activate new account
- :heavy_check_mark: as new account - re-login, expected session still active
- :heavy_check_mark: as admin - delete new account

## Miscellaneous
- :heavy_check_mark: create public link with password
- :heavy_check_mark: update password and reload, expected no access
- :heavy_check_mark: delete large folder and recover it
- :heavy_check_mark: create version of textfile
- :heavy_check_mark: view version history of text file
- :heavy_check_mark: download newest version of text file
- :x: download older version of text file

**Comment by pascalwengerter** [comment]
# Smoke testing on https://localhost:9200/ on macOS (M1) & Firefox 87.0
## Files

    ✔️ login as einstein
    ✔️ create a folder "eBooks"
    ✔️ share "eBooks" with marie as viewer
    ✔️ share "eBooks" with richard as editor
    ✔️ create a subfolder "eBooks/test"
    ✔️ upload "paper.pdf" into "eBooks/test"
    ✔️ upload "image.jpg" into "/"
    ✔️ copy "image.jpg" into "eBooks"
    ✔️ move "image.jpg" into "eBooks/test"
    ✔️ share "eBooks" as unprotected public link with viewer role
        ✔️ access unprotected public link
        ✔️ no write actions available on files, folders, subfolders, files in subfolders
        ✔️ download of files works (doublecheck in OS filebrowser)
        ❌ viewing images in mediaviewer doesn't work - known issue #1075
    ✔️ share "eBooks" as password protected public link with editor role
        ✔️ access password protected public link
        ✔️ write actions available on files, folders, subfolders, files in subfolders
        ✔️ deleting files and folders works and is visible to share owner
        ✔️ renaming files and folders works and is visible to share owner
        ✔️ uploading files works and is visible to share owner
        ✔️ download of files works (doublecheck in OS filebrowser)
        ❌ viewing images in mediaviewer doesn't work - known issue #1075
    ❌ restoring a file from the trahsbin that was deleted from within a public link fails
    ✔️ permanently deleting a file from the trashbin works
    ✔️ clearing the trashbin works
    ✔️ login as richard
        ✔️ accept "eBooks" share
        ✔️ browse into "eBooks" share by clicking on it in "Shared with me"
        ✔️ see breadcrumbs as "/Shares/eBooks"
        ✔️ browse into "test" subfolder
        ✔️ open "image.jpg" in mediaviewer
        ✔️ close mediaviewer, land in "/Shares/eBooks/test" in the files app again
        ✔️ open right sidebar (details) for "image.jpg"
        ✔️ rename "image.jpg" to "renamed-by-richard.jpg"
        ✔️ download of "renamed-by-richard.jpg" works (doublecheck in OS filebrowser)
        ✔️ re-upload "renamed-by-richard.jpg", creating a new version (= replacing the old one)
        ❌ download older version of "renamed-by-richard.jpg" fails (501 - not implemented)
        ❌ restoring older version creates a new version - known issue #1214
    ✔️ login as marie
        ✔️ accept "eBooks" share
        ✔️ browse into "eBooks" share by going to "All files" and browsing into "/Shares/eBooks"
        ✔️ browse into "test" subfolder
        ✔️ open "renamed-by-richard.jpg" in mediaviewer
        ✔️ close mediaviewer, land in "/Shares/eBooks/test" in the files app again
        ✔️ open right sidebar (details) for "renamed-by-richard.jpg"
        ✔️ action "Rename" is not available in the right sidebar
        ✔️ action "Move" is not available in the right sidebar
        ✔️ action "Delete" is not available in the right sidebar
        ✔️ check the checkbox for "renamed-by-richard.jpg" in the files list
        ✔️ action "Move" is not available in the batch actions at the top
        ❌ action "Delete" is available in the batch actions at the top (but doesn't work / produce an error)

## Settings

    ✔️ login as marie
    ✔️ go to settings page by clicking on username (top right) and clicking on "Settings"
    ✔️ select "Deutsch" as language
    ✔️ nav items in the left sidebar are displayed in german language
    ✔️ browse to files app
    ✔️ nav items in the left sidebar are displayed in german language
    ✔️ table header and footer of the "All files" list are displayed in german language
    ✔️ button and sub-actions for creating new resources is displayed in german language
    ✔️ logout and then login as richard
    ✔️ all UI elements mentioned before are again displayed in english language (as language for richard was not changed)

**Comment by fschade** [comment]
# K6 results on intel test machine

## 1.4.0
```
```

## History
* [1.3.0](https://github.com/owncloud/ocis/issues/1775#issuecomment-793118621)
* [1.1.0](https://github.com/owncloud/ocis/issues/1365#issuecomment-765391977)
