### ISSUE TITLE
Ocis 1.0.0-beta3

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#202]
# Tasks

## ocis-konnectd
- [x] Tag a new Release `v.0.3.0`

## Phoenix
- [x] Release v0.8.0
- [x] Release ocis-phoenix v0.5.0

## Reva
- [x]  Update cs3org reva https://github.com/owncloud/ocis-reva/pull/134
- [x]  Tag [v0.2.0](https://github.com/owncloud/ocis-reva/releases/tag/v0.2.0) release for ocis-reva 

## OCIS

- [x] Update ocis-reva
- [x] Update ocis-proxy
- [x] Update ocis-phoenix
- [x] Update ocis-konnectd
- [x] Tag oCIS 1.0.0-beta3
