### ISSUE TITLE
Release oCIS 1.7.0

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#2102]
## Tasks
- [ ] Brief marketing heads up @pmaier1
- [x] release web [v3.2.0-rc1](https://github.com/owncloud/web/releases/tag/v3.2.0-rc1) @kulmann 
  - [x] update to web [v3.2.0-rc1](https://github.com/owncloud/ocis/pull/2096) in ocis @kulmann
  - [x]  smoke testing for web v3.2.0-rc1 @LukasHirt @pascalwengerter  -> succeeded
- [x] release web [v3.2.0 final](https://github.com/owncloud/web/releases/tag/v3.2.0) @kulmann 
  - [x] update to web [v3.2.0](https://github.com/owncloud/ocis/pull/2096) in ocis @kulmann 
- [x] update to reva current master https://github.com/owncloud/ocis/pull/2104 @C0rby
- [x] Release Notes https://github.com/owncloud/ocis/pull/2110 @pmaier1 
- [X] create a web PR which updates the ocis commit id, so that we have a final web UI CI run against latest ocis @kulmann (https://github.com/owncloud/web/pull/5179/files)
- [x] Create branch `release-1.7.0` -> CODEFREEZE @micbar 
- [x] Prepare Changelog @micbar 
- [x] Create pre release tag `v1.7.0-rc1` @micbar 
- [x] Smoke Test @kulmann @ScharfViktor 
- [x] Compatibility test / upgrade test @ScharfViktor 
- [x] run K6 on the tag @fschade 
- [ ] If needed, fix issues or write down known issues alert in chat
- [x] Create final signed tag `v1.7.0` @micbar 
- [x] Merge release notes @micbar 
- [x] Check successful CI run on v1.7.0 tag @micbar 
- [x] Ping marketing to update all download links @micbar 
- [x] Merge back release branch https://github.com/owncloud/ocis/pull/2134 @micbar

**Comment by fschade** [comment]
# TBD 

Create these with the original oCIS version and see if still the same after upgrading:
- shares
  - [ ] public share without password, without expiration
  - [ ] public share with password, without expiration
  - [ ] public share with password, with expiration
  - [ ] share with user as role editor
  - [ ] share with user as role viewer
- settings
  - [ ] language settings
- files
  - [ ] uploaded folder & files
  - [ ] trashed files
- users
  - [ ] non demo user with role admin
  - [ ] non demo user with role user

**Comment by fschade** [comment]
# TBD

# K6 results on intel test machine


## 1.7.0 
```
```

## History
* [1.6.0](https://github.com/owncloud/ocis/issues/2043#issuecomment-841160859)
* [1.6.0-network](https://gist.github.com/fschade/fa8d2af28fdc45177fe1327708e1301c)
* [1.5.0-network](https://github.com/owncloud/ocis/issues/1927#issuecomment-824354118)
* [1.4.0-network](https://github.com/owncloud/ocis/issues/1866#issuecomment-810852379)
* [1.3.0-network](https://github.com/owncloud/ocis/issues/1775#issuecomment-793118621)
* [1.1.0-network](https://github.com/owncloud/ocis/issues/1365#issuecomment-765391977)

with the release of `1.6.0` we started to test on localhost to prevent network latency, the results are not comparable to previous tests anymore.

**Comment by kulmann** [comment]
# Smoke testing on https://localhost:9200/ on macOS with tag v1.7.0-rc1

## Files
- ✔️ login as einstein
- ✔️ create a folder "eBooks"
- ✔️ share "eBooks" with marie as viewer
- ✔️share "eBooks" with richard as editor
- ✔️ create a subfolder "eBooks/test"
- ✔️ upload "paper.pdf" into "eBooks/test"
- ✔️ upload "image.jpg" into "/"
- ✔️ copy "image.jpg" into "eBooks"
- ✔️ move "image.jpg" into "eBooks/test"
- ✔️ share "eBooks" as unprotected public link with viewer role
  - ✔️ access unprotected public link
  - ✔️ no write actions available on files, folders, subfolders, files in subfolders
  - ✔️ download of files works (doublecheck in OS filebrowser)
  - ✔️ viewing images in mediaviewer works
  - ❌ folders show a `?` as size https://github.com/owncloud/web/issues/4995
  - ✔️ previews in file list work
- ✔️ share "eBooks" as password protected public link with editor role
  - ✔️ access password protected public link
  - ✔️ write actions available on files, folders, subfolders, files in subfolders
  - ✔️ deleting files and folders works and is visible to share owner
  - ✔️ renaming files and folders works and is visible to share owner
  - ✔️ uploading files works and is visible to share owner
  - ✔️ download of files works (doublecheck in OS filebrowser)
  - ✔️ viewing images in mediaviewer works
  - ❌ folders show a `?` as size https://github.com/owncloud/web/issues/4995
  - ✔️ previews in file list work
- ❌ restoring a file from the trahsbin that was deleted from within a public link fails
- ✔️ permanently deleting a file from the trashbin works
- ✔️ clearing the trashbin works
- ✔️ login as richard
  - ✔️ accept "eBooks" share
  - ✔️ browse into "eBooks" share by clicking on it in "Shared with me"
  - ✔️ see breadcrumbs as "/Shares/eBooks"
  - ✔️ browse into "test" subfolder
  - ✔️ open "image.jpg" in mediaviewer
  - ✔️ close mediaviewer, land in "/Shares/eBooks/test" in the files app again
  - ✔️ open right sidebar (details) for "image.jpg"
  - ✔️ rename "image.jpg" to "renamed-by-richard.jpg"
  - ✔️ download of "renamed-by-richard.jpg" works (doublecheck in OS filebrowser)
  - ❌ re-upload "renamed-by-richard.jpg", creating a new version -> works, but shows the file duplicated until the page is reloaded https://github.com/owncloud/web/issues/4996
  - ❌ download older version of "renamed-by-richard.jpg" fails (501 - not implemented)
  - ❌ restoring older version creates a new version - [known issue #1214](https://github.com/owncloud/ocis/issues/1214)
- ✔️ login as marie
  - ✔️ accept "eBooks" share
  - ✔️ browse into "eBooks" share by going to "All files" and browsing into "/Shares/eBooks"
  - ✔️ browse into "test" subfolder
  - ✔️ open "renamed-by-richard.jpg" in mediaviewer
  - ✔️ close mediaviewer, land in "/Shares/eBooks/test" in the files app again
  - ✔️ open right sidebar (details) for "renamed-by-richard.jpg"
  - ✔️ action "Rename" is not available in the right sidebar
  - ✔️ action "Move" is not available in the right sidebar
  - ✔️ action "Delete" is not available in the right sidebar
  - ✔️ check the checkbox for "renamed-by-richard.jpg" in the files list
  - ✔️ action "Move" is not available in the batch actions at the top
  - ❌ action "Delete" is available in the batch actions at the top (but throws an error upon using it)


## Settings
- ✔️ login as marie
- ✔️ go to settings page by clicking on username (top right) and clicking on "Settings"
- ✔️ select "Deutsch" as language
- ✔️ nav items in the left sidebar are displayed in german language
- ✔️ browse to files app
- ✔️ nav items in the left sidebar are displayed in german language
- ✔️ table header and footer of the "All files" list are displayed in german language
- ✔️ button and sub-actions for creating new resources is displayed in german language
- ✔️ logout and then login as richard
- ✔️ all UI elements mentioned before are again displayed in english language (as language for richard was not changed)

## Conclusion
### new issues
none 🥳 

### Things that were fixed, compared to the last release
  - RESOLVED: accept "eBooks" share -> works, but shows `Pending` as status after accepting. https://github.com/cs3org/reva/issues/1684
  - RESOLVED: browse into "eBooks" share by clicking on it in "Shared with me" -> new issue. Share that is returned on get by id doesn't have the correct file target.

**Comment by ScharfViktor** [comment]
Smoke testing on https://localhost:9200/ on macOS with tag v1.7.0-rc1
Files
✔️ login as einstein
✔️ create a folder "eBooks"
✔️ share "eBooks" with marie as viewer
✔️share "eBooks" with richard as editor
✔️ create a subfolder "eBooks/test"
✔️ upload "paper.pdf" into "eBooks/test"
✔️ upload "image.jpg" into "/"
✔️ copy "image.jpg" into "eBooks"
✔️ move "image.jpg" into "eBooks/test"
✔️ share "eBooks" as unprotected public link with viewer role
✔️ access unprotected public link
✔️ no write actions available on files, folders, subfolders, files in subfolders
✔️ download of files works (doublecheck in OS filebrowser)
✔️ viewing images in mediaviewer works
repeated ❌ folders show a ? as size https://github.com/owncloud/web/issues/4995
✔️ previews in file list work
✔️ share "eBooks" as password protected public link with editor role
✔️ access password protected public link
✔️ write actions available on files, folders, subfolders, files in subfolders
✔️ deleting files and folders works and is visible to share owner
✔️ renaming files and folders works and is visible to share owner
✔️ uploading files works and is visible to share owner
✔️ download of files works (doublecheck in OS filebrowser)
✔️ viewing images in mediaviewer works
❌ folders show a ? as size https://github.com/owncloud/web/issues/4995
✔️ previews in file list work
❌ restoring a file from the trahsbin that was deleted from within a public link fails
✔️ permanently deleting a file from the trashbin works
✔️ clearing the trashbin works
✔️ login as richard
✔️ accept "eBooks" share
✔️ browse into "eBooks" share by clicking on it in "Shared with me"
✔️ see breadcrumbs as "/Shares/eBooks"
✔️ browse into "test" subfolder
✔️ open "image.jpg" in mediaviewer
✔️ close mediaviewer, land in "/Shares/eBooks/test" in the files app again
✔️ open right sidebar (details) for "image.jpg"
✔️ rename "image.jpg" to "renamed-by-richard.jpg"
✔️ download of "renamed-by-richard.jpg" works (doublecheck in OS filebrowser)
❌ re-upload "renamed-by-richard.jpg", creating a new version -> works, but shows the file duplicated until the page is reloaded owncloud/web#4996
❌ download older version of "renamed-by-richard.jpg" fails (501 - not implemented)
❌ restoring older version creates a new version - known issue #1214
✔️ login as marie
✔️ accept "eBooks" share
✔️ browse into "eBooks" share by going to "All files" and browsing into "/Shares/eBooks"
✔️ browse into "test" subfolder
✔️ open "renamed-by-richard.jpg" in mediaviewer
✔️ close mediaviewer, land in "/Shares/eBooks/test" in the files app again
✔️ open right sidebar (details) for "renamed-by-richard.jpg"
✔️ action "Rename" is not available in the right sidebar
✔️ action "Move" is not available in the right sidebar
✔️ action "Delete" is not available in the right sidebar
✔️ check the checkbox for "renamed-by-richard.jpg" in the files list
✔️ action "Move" is not available in the batch actions at the top
❌ action "Delete" is available in the batch actions at the top (but throws an error upon using it)
Settings
✔️ login as marie
✔️ go to settings page by clicking on username (top right) and clicking on "Settings"
✔️ select "Deutsch" as language
✔️ nav items in the left sidebar are displayed in german language
✔️ browse to files app
✔️ nav items in the left sidebar are displayed in german language
✔️ table header and footer of the "All files" list are displayed in german language
✔️ button and sub-actions for creating new resources is displayed in german language
✔️ logout and then login as richard
✔️ all UI elements mentioned before are again displayed in english language (as language for richard was not changed)

❌ Marie with role "User" try to create new User **expected result**: 403 Forbidden  or hide creation functionality.  **actual result**: 400 Bad request

❌ usability bug: When you use the mobile version or squeeze the screen the sidebar goes all the way to the screen

❌ "Edit share" for people doesn't work in the next case: 
1. Open sidebar
2. Chose "Shared with other" - here important
3. Open an action for shared folder and click "edit share" for people
expected result: the request is not sent. content "people" collapse

Conclusion:
The remarks are not critical. The release is ready
