### ISSUE TITLE
[EPIC] In place migration of oc10 to ocis

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#22]
# In place migration of oc10 to ocis

Milestone issue list: [Migration](https://github.com/owncloud/ocis/milestone/2)

## Scenario

_This scenario is based on [the one](https://github.com/owncloud/data_exporter/issues/20#issuecomment-422051301) for [the data_exporter requirements](https://github.com/owncloud/data_exporter/issues/20)._

Given an instance at https://demo.owncloud.com where user `einstein` shared a folder `/photos` with `marie` who mounted it as `/projects/abc` this is the flow that is planned to migrate an instance user by user:
- [ ] cover reshares
- [ ] cover (re-)shares to groups

### 0. Prerequisites
- [ ] Document how to set up OIDC auth and phoenix for oc10
  - https://github.com/owncloud/openidconnect openidconnect support for core
  - https://github.com/owncloud/core/issues/34484 Phoenix integration into core
  - we assume the oidc idp/iss is https://idp.owncloud.com

### 1. Set up reverse proxy
1. make oc10 available at https://oc10.owncloud.com as well
2. Introduce OCIS as proxy for https://demo.owncloud.com
  - [ ] add proxy middleware for reva

OCIS is used to forward requests for unmigrated users to the oc10 instance/domain.
- it keeps a list of migrated users do decide which requests to forward

Migrated users will be hosted by ocis

### 2. Migrate groups (optional)
Can be skipped if all groups are maintained in an LDAP server that has been configured for oc10 & ocis
- [ ] `occ export:groups` TODO there is only `occ groups:list`
- [ ] `occ import:groups` TODO use `occ group:add`

### 3. Migrate user by user

1. in oc10 export user file and share metadata: `occ export:user einstein`, `occ export:user marie`, `occ export:user richard`
  - will export file and share metadata.
    - [x] basic data format is in place: see https://github.com/owncloud/data_exporter/issues/77
    - [ ] share recipient has no mount point information, but we need it to reconstruct the shares. tracked in https://github.com/owncloud/data_exporter/issues/113
    - the file metadata contains a reference to the share that allows reconstructing the storage and path to the shared file, eg `/projects/abc` is a reference to type `home` user `einstein` and path `/photos`
  - nothing is changed in either instance, a reexport can happen at any time
  - TODO create a milestone in the data exporter for needed changes/fixes for these
    - [ ] [Make file export optional ](https://github.com/owncloud/data_exporter/issues/97)
    - [ ] [drop `/files` prefix for path in files.jsonl](https://github.com/owncloud/data_exporter/issues/111)
    - [ ] [export mount points](https://github.com/owncloud/data_exporter/issues/113)
    - [ ] [reshares are exported with path `null`](https://github.com/owncloud/data_exporter/issues/114)
    - [ ] [Add Extended Share attributes](https://github.com/owncloud/data_exporter/issues/96)

2. in ocis `reva import marie --user-iss https://idp.owncloud.com --user-sub cb1dd81e-6967-44f7-8239-dffbbe319e92`
  - imports the user `marie` with iss `https://idp.owncloud.com` and sub `cb1dd81e-6967-44f7-8239-dffbbe319e92` into ocis
    - [ ] create the storage if the user does not exist yet
    - [ ] add storage registry entry? for now the static registry will use the same storage provider for all the users.
  - [x] shares to migrated users are recreated as internal shares (for the first user, no shares will be migrated)
    - [ ] due to path based references we need to have the list of oc10 usernames to ocis sub@iss mappings available to properly rewrite the userid in references
  - [ ] shares to not migrated users are created as federated shares to the old instance
    - [ ] with a user id mapping file we can set the permissions in the storage
    - [ ] implement a handler for the federated sharing api
      - [ ] needs an auth provider for the federated sharing id
  - [ ] shares from migrated users are mounted
    - can be determined if the exported reference can be resolved to an existing file/folder, including the userid mapping
  - shares from non migrated users are skipped, they will be migrated in the next step
  - [ ] public shares are recreated with the same token
  - [ ] import file metadata, WIP PR https://github.com/cs3org/reva/pull/299 needs https://github.com/cs3org/reva/pull/289

Repeat the import and export for as many users as desired

3. s1: `occ migrate:shares marie https://demo.owncloud.com`
  - shares to `marie` are converted into federated shares to `marie@demo.owncloud.com`
    - [ ] use a username -> iss & sub mapping file
    - creating federated shares will send a federated sharing request to ocis... or not because oc10 thinks it is still responsible for both domains.
    - needs to be done using sql
    - [ ]  the command needs an API to create shares in OCIS
      - for shares from/to migrated users, internal shares are set up
      - for shares from/to non migrated users, federated shares are created.

4. s1: `occ user:delete marie`
  - but without actually deleting files?
  - mark user as migrated for the proxy

5. migrate trash in a dedicated step?
6. migrate versions in a dedicated step?

## migrate data (file content)
- [ ] data needs to be moved from old ownCloud data directory into new eos layout
  - no files (files_trashbin, files_versions) folder per user, we need to move files to new user home
    - to import versions into EOS, see [below](https://github.com/owncloud/ocis/issues/22#issuecomment-522893692)
    - to import trash into EOS, see [below](https://github.com/owncloud/ocis/issues/22#issuecomment-522893692)
  - owner changes from www-data to the actual user (users must be known to the underlying os, so ACLs can be set up correctly)

## proxy
- [ ] user by user migration needs to send users to either revad or oc10 apache servers
  - task for the authentication / reverse proxy, likely a header that is set during login
  - can we make reva act as a proxy for the old oc10 so we can intercept the traffic and send users to the right instance
    - would that help with sharing?
    - would this allow sharding instances
- [ ] how do we authenticate users
  - phoenix supports oidc and oauth2, but no basic auth
  - revad supports oidc and can use basic auth
  - since we have to control the users anyway, in order to set ACLs for guest accounts we may have to manage our own ldap server that can then be used to provide users for an oidc capable IdP

**Comment by butonic** [comment]
- [ ] how do we import versions and trash items via the CS3 api?

**Comment by refs** [comment]
efforts on https://github.com/owncloud/ocis-migration supercede this issue. See https://owncloud.github.io/ocis/deployment/#migrate-an-existing-owncloud-10

**Comment by jnweiger** [comment]
Elcin's implementation: https://github.com/esgarov/Daten-Import-in-Ocis
