### ISSUE TITLE
ocis 1.0.0-beta6 

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#332]
## Tasks
- [x] Integrate TUS endpoint with ocis-proxy https://github.com/owncloud/product/issues/72
   - [x] update reva in ocis-reva: https://github.com/owncloud/ocis-reva/pull/261
   - [x] release ocis-proxy (with the reva TUS fix)
   - [x] release ocis-migration (with some fix for a compilation issue related to accounts API)
   - [x] release ocis-reva (with the reva changes for the TUS fix for proxy)
- [x] public link upload/download
   - [x] update reva in ocis-reva: https://github.com/owncloud/ocis-reva/pull/261
- [x] ocis-reva EOS change in storage drivers names
- [x] ocis-reva release
- [x] ocis-phoenix release https://github.com/owncloud/ocis-phoenix/releases/tag/v0.8.0
- [x] Auto Create home folders
- [x] Release phoenix
- [x] Release ocis-phoenix
- [x] update go.mod in ocis for ocis-proxy, ocis-migration and ocis-reva: https://github.com/owncloud/ocis/pull/334
- [x] release ocis-beta6

## Out of scope
- ~~Single file sharing~~ it's in!
- New ocis accounts features
- Permission handling in shares
- Public link password check not enforced for API access (only first access in UI): https://github.com/owncloud/ocis-reva/issues/312

**Comment by PVince81** [comment]
Due to additional issues we'll need to release the following modules:
- [ ] release ocis-proxy (with the reva TUS fix)
- [ ] release ocis-migration (with some fix for a compilation issue related to accounts API)
- [ ] release ocis-reva (with the reva changes for the TUS fix for proxy)
- [ ] update go.mod in ocis for ocis-proxy, ocis-migration and ocis-reva

**Comment by micbar** [comment]
@HanaGemela @felixboehm JFYI

**Comment by PVince81** [comment]
https://github.com/owncloud/ocis-reva/pull/261 was merged so ocis-proxy (TUS) and public link stuff is merged.

next up is fixing EOS config in ocis-reva

**Comment by PVince81** [comment]
@micbar I've added "permission handling" in "out of scope" as I remembered that it's not implemented. See https://github.com/owncloud/ocis-reva/issues/292

in case it matters for communication

**Comment by PVince81** [comment]
added to "out of scope": Public link password check not enforced for API access (only first access in UI)

it's not implemented yet.

**Comment by PVince81** [comment]
the release is out: https://github.com/owncloud/ocis/releases/tag/v1.0.0-beta6
