### ISSUE TITLE
 Release 1.19.0 Tech Preview

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#3377]
## Tasks
- [x] Brief marketing heads up @pascalwengerter 
- [x] Update web to 5.3.0 https://github.com/owncloud/ocis/pull/3375 @pascalwengerter 
- [x] update to REVA v2.x.x https://github.com/owncloud/ocis/pull/3405
- [x] Release Reva `v2.1.0` https://github.com/cs3org/reva/pull/2690
- [x] Update Reva to `v2.1.0` https://github.com/owncloud/ocis/pull/3416
   - [x] clean up our changelog regarding reva updates (there should be only one)
- [x] Create branch `release-1.19.0` -> CODEFREEZE
- [x] Prepare Changelog 
- [x] Release Notes @micbar https://github.com/owncloud/ocis/pull/3422
- [x] Create pre release tag `v1.19.0-rc1`
- [x] Smoke Test @ScharfViktor 
  - [x] with oCIS WOPI server @wkloucek -> failed (see comments below) -> no blocker
  - [x] with oCIS Hello extension @wkloucek -> failed (see comments below) -> no blocker
- [x] Compatibility test / upgrade test @wkloucek -> failed (see comments below) -> no blocker
- [x] run K6 on the tag @ScharfViktor 
- [x] If needed, fix issues or write down known issues alert in chat
- [x] Create final signed tag `v1.19.0`  
- [x] Merge release notes
- [x] Check successful CI run on `v1.19.0` tag 
- [x] Ping marketing to update all download links  
- [x] Merge back release branch https://github.com/owncloud/ocis/pull/3418
- [x] Ping @hodyroff once the demo instances are running this release

**Comment by micbar** [comment]
# Changes in 1.19.0

## Summary

* Bugfix - Network configuration in individiual_services example: [#3238](https://github.com/owncloud/ocis/pull/3238)
* Bugfix - Improve gif thumbnails: [#3305](https://github.com/owncloud/ocis/pull/3305)
* Bugfix - Fix error handling in GraphAPI GetUsers call: [#3357](https://github.com/owncloud/ocis/pull/3357)
* Bugfix - Fix request validation on GraphAPI User updates: [#3167](https://github.com/owncloud/ocis/issues/3167)
* Bugfix - Replace public mountpoint fileid with grant fileid: [#3349](https://github.com/owncloud/ocis/pull/3349)
* Change - Add remote item to mountpoint and fix spaceID: [#3365](https://github.com/owncloud/ocis/pull/3365)
* Change - Switch NATS backend: [#3192](https://github.com/owncloud/ocis/pull/3192)
* Change - Drop json config file support: [#3366](https://github.com/owncloud/ocis/pull/3366)
* Change - Settings service now stores its data via metadata service: [#3232](https://github.com/owncloud/ocis/pull/3232)
* Enhancement - Audit logger will now log file events: [#3332](https://github.com/owncloud/ocis/pull/3332)
* Enhancement - Add password reset link to login page: [#3329](https://github.com/owncloud/ocis/pull/3329)
* Enhancement - Log sharing events in audit service: [#3301](https://github.com/owncloud/ocis/pull/3301)
* Enhancement - Add space aliases: [#3283](https://github.com/owncloud/ocis/pull/3283)
* Enhancement - Include etags in drives listing: [#3267](https://github.com/owncloud/ocis/pull/3267)
* Enhancement - Improve thumbnails API: [#3272](https://github.com/owncloud/ocis/pull/3272)
* Enhancement - Update reva to v2.1.0: [#3330](https://github.com/owncloud/ocis/pull/3330)
* Enhancement - Update ownCloud Web to v5.3.0: [#6561](https://github.com/owncloud/web/pull/6561)

## Details

* Bugfix - Network configuration in individiual_services example: [#3238](https://github.com/owncloud/ocis/pull/3238)

   Tidy up the deployments/examples/ocis_individual_services example so that the
   instructions work.

   https://github.com/owncloud/ocis/pull/3238

* Bugfix - Improve gif thumbnails: [#3305](https://github.com/owncloud/ocis/pull/3305)

   Improved the gif thumbnail generation for gifs with different disposal strategies.

   https://github.com/owncloud/ocis/pull/3305

* Bugfix - Fix error handling in GraphAPI GetUsers call: [#3357](https://github.com/owncloud/ocis/pull/3357)

   A missing return statement caused GetUsers to return misleading results when the identity
   backend returned an error.

   https://github.com/owncloud/ocis/pull/3357

* Bugfix - Fix request validation on GraphAPI User updates: [#3167](https://github.com/owncloud/ocis/issues/3167)

   Fix PATCH on graph/v1.0/users when no 'mail' attribute is present in the request body

   https://github.com/owncloud/ocis/issues/3167

* Bugfix - Replace public mountpoint fileid with grant fileid: [#3349](https://github.com/owncloud/ocis/pull/3349)

   We now show the same resoucre id for resources when accessing them via a public links as when
   using a logged in user. This allows the web ui to start a WOPI session with the correct resource
   id.

   https://github.com/owncloud/ocis/pull/3349

* Change - Add remote item to mountpoint and fix spaceID: [#3365](https://github.com/owncloud/ocis/pull/3365)

   A mountpoint represents the mounted share on the share receivers side. The original resource
   is located where the grant has been set. This item is now shown as libregraph remoteItem on the
   mountpoint. While adding this, we fixed the spaceID for mountpoints.

   https://github.com/owncloud/ocis/pull/3365

* Change - Switch NATS backend: [#3192](https://github.com/owncloud/ocis/pull/3192)

   We've switched the NATS backend from Streaming to JetStream, since NATS Streaming is
   depreciated.

   https://github.com/owncloud/ocis/pull/3192
   https://github.com/cs3org/reva/pull/2574

* Change - Drop json config file support: [#3366](https://github.com/owncloud/ocis/pull/3366)

   We've remove the support to configure oCIS and it's service with a json file. From now on we only
   support yaml configuration files, since they have the possibility to add comments.

   https://github.com/owncloud/ocis/pull/3366

* Change - Settings service now stores its data via metadata service: [#3232](https://github.com/owncloud/ocis/pull/3232)

   Instead of writing files to disk it will use metadata service to do so

   https://github.com/owncloud/ocis/pull/3232

* Enhancement - Audit logger will now log file events: [#3332](https://github.com/owncloud/ocis/pull/3332)

   See full list of supported events in `audit/pkg/types/types.go`

   https://github.com/owncloud/ocis/pull/3332

* Enhancement - Add password reset link to login page: [#3329](https://github.com/owncloud/ocis/pull/3329)

   Added a configurable passwort reset link to the login page. It can be set via
   `IDP_PASSWORD_RESET_URI`. If the option is not set the link will not be shown.

   https://github.com/owncloud/ocis/pull/3329

* Enhancement - Log sharing events in audit service: [#3301](https://github.com/owncloud/ocis/pull/3301)

   Contains sharing related events. See full list in audit/pkg/types/events.go

   https://github.com/owncloud/ocis/pull/3301

* Enhancement - Add space aliases: [#3283](https://github.com/owncloud/ocis/pull/3283)

   Space aliases can be used to resolve spaceIDs in a client.

   https://github.com/owncloud/ocis/pull/3283

* Enhancement - Include etags in drives listing: [#3267](https://github.com/owncloud/ocis/pull/3267)

   Added etags in the response of list drives.

   https://github.com/owncloud/ocis/pull/3267

* Enhancement - Improve thumbnails API: [#3272](https://github.com/owncloud/ocis/pull/3272)

   Changed the thumbnails API to no longer transfer images via GRPC. GRPC has a limited message
   size and isn't very efficient with large binary data. The new API transports the images over
   HTTP.

   https://github.com/owncloud/ocis/pull/3272

* Enhancement - Update reva to v2.1.0: [#3330](https://github.com/owncloud/ocis/pull/3330)

   Updated reva to version 2.1.0. This update includes:

  * Fix [cs3org/reva#2636](https://github.com/cs3org/reva/pull/2636): Delay reconnect log for events
  * Fix [cs3org/reva#2645](https://github.com/cs3org/reva/pull/2645): Avoid warning about missing .flock files
  * Fix [cs3org/reva#2625](https://github.com/cs3org/reva/pull/2625): Fix locking on publik links and the decomposed filesystem
  * Fix [cs3org/reva#2643](https://github.com/cs3org/reva/pull/2643): Emit linkaccessfailed event when share is nil
  * Fix [cs3org/reva#2646](https://github.com/cs3org/reva/pull/2646): Replace public mountpoint fileid with grant fileid in ocdav
  * Fix [cs3org/reva#2612](https://github.com/cs3org/reva/pull/2612): Adjust the scope handling to support the spaces architecture
  * Fix [cs3org/reva#2621](https://github.com/cs3org/reva/pull/2621): Send events only if response code is `OK`
  * Chg [cs3org/reva#2574](https://github.com/cs3org/reva/pull/2574): Switch NATS backend
  * Chg [cs3org/reva#2667](https://github.com/cs3org/reva/pull/2667): Allow LDAP groups to have no gidNumber
  * Chg [cs3org/reva#3233](https://github.com/cs3org/reva/pull/3233): Improve quota handling
  * Chg [cs3org/reva#2600](https://github.com/cs3org/reva/pull/2600): Use the cs3 share api to manage spaces
  * Enh [cs3org/reva#2644](https://github.com/cs3org/reva/pull/2644): Add new public share manager
  * Enh [cs3org/reva#2626](https://github.com/cs3org/reva/pull/2626): Add new share manager
  * Enh [cs3org/reva#2624](https://github.com/cs3org/reva/pull/2624): Add etags to virtual spaces
  * Enh [cs3org/reva#2639](https://github.com/cs3org/reva/pull/2639): File Events
  * Enh [cs3org/reva#2627](https://github.com/cs3org/reva/pull/2627): Add events for sharing action
  * Enh [cs3org/reva#2664](https://github.com/cs3org/reva/pull/2664): Add grantID to mountpoint
  * Enh [cs3org/reva#2622](https://github.com/cs3org/reva/pull/2622): Allow listing shares in spaces via the OCS API
  * Enh [cs3org/reva#2623](https://github.com/cs3org/reva/pull/2623): Add space aliases
  * Enh [cs3org/reva#2647](https://github.com/cs3org/reva/pull/2647): Add space specific events
  * Enh [cs3org/reva#3345](https://github.com/cs3org/reva/pull/3345): Add the spaceid to propfind responses
  * Enh [cs3org/reva#2616](https://github.com/cs3org/reva/pull/2616): Add etag to spaces response
  * Enh [cs3org/reva#2628](https://github.com/cs3org/reva/pull/2628): Add spaces aware trash-bin API

   https://github.com/owncloud/ocis/pull/3330
   https://github.com/owncloud/ocis/pull/3405
   https://github.com/owncloud/ocis/pull/3416

* Enhancement - Update ownCloud Web to v5.3.0: [#6561](https://github.com/owncloud/web/pull/6561)

   Tags: web

   We updated ownCloud Web to v5.3.0. Please refer to the changelog (linked) for details on the web
   release.

   https://github.com/owncloud/web/pull/6561
   https://github.com/owncloud/ocis/pull/3291
   https://github.com/owncloud/ocis/pull/3375
   https://github.com/owncloud/web/releases/tag/v5.3.0

**Comment by wkloucek** [comment]
# Smoke test with [oCIS Hello](https://github.com/owncloud/ocis-hello)
- [ ] [Docker-Compose Setup](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_hello)
- [ ] Login as Einstein
   - [ ] Navigate to Hello Extension (via app drawer)
   - [ ] Type "foo" and submit -> receive "Hello foo"
   - [ ] Navigate to settings and make sure there are no Hello configuration options
- [ ] Login as Admin
   - [ ] Navigate to Hello Extension (via app drawer)
   - [ ] Type "bar" and submit -> receive "Hello bar"
   - [ ] Navigate to settings -> Hello and change the greeter message to "Bonjour"
   - [ ] Navigate to Hello Extension (via app drawer)
   - [ ] Type "bar" and submit -> receive "Bonjour bar"
- [ ] Login as Einstein
   - [ ] Navigate to Hello Extension (via app drawer)
   - [ ] Type "foo" and submit -> receive "Bonjour foo"

## Findings
- Design and layout is off, but functionality is ok. PR for design and layout already is WIP: https://github.com/owncloud/ocis-hello/pull/130

**Comment by wkloucek** [comment]
# Compatibility test from v1.18.0 to v1.19.0-rc1

## Create these with the original oCIS version and see if still the same after upgrading:
- shares
  - [ ] public share
  - [ ] share with user as role editor
  - [ ] share with user as role viewer
- settings
  - [ ] language settings
- files
  - [ ] uploaded folder & files
  - [ ] trashed files
- users
  - [ ] non demo user with role admin
  - [ ] non demo user with role user


## additional issues:
- none

**Comment by wkloucek** [comment]
# Smoke test with ~[oCIS WOPI server](https://github.com/owncloud/ocis-wopiserver)~ [wkloucek/cs3-wopi-server](https://github.com/wkloucek/cs3-wopi-server/pull/1)

- [ ] ~[Docker-Compose Setup](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_wopi)~ [Docker-Compose Setup](https://github.com/owncloud/ocis/pull/3333)
- [] Login as Einstein
   - [ ] ~Go to all files -> Click "Create new file" -> You have multiple proposed office formats~ Not yet implemented
   - [ ] Upload an `.odt` file ~Create a new "odt" office file~
      - [ ] ~file opens~ open file in Collabora
      - [ ] add some text, save the file and close the editor / tab
      - [ ] reopen the newly created file
      - [ ] the previously added text is still there
   - [ ] ~Upload an `.md` file~ ~Create a new "md" file~
      - [ ] ~file opens~ ~open file in CodiMD~
      - [ ] ~add some text, save the file and close the editor / tab~
      - [ ] ~reopen the newly created file~
      - [ ] ~the previously added text is still there~
   - [ ] Upload an `.docx` file ~Create a new "docx" file~
      - [ ] ~file opens~ open file in OnlyOffice
      - [ ] add some text, save the file and close the editor / tab
      - [ ] reopen the newly created file
      - [ ] the previously added text is still there
      - [ ] copy the URL of the open file view in OnlyOffice
      - [ ] open the URL in a new incognito tab (with no session)
      - [ ] be redirected to the login screen and then login in as Einstein 
      - [ ] see the file opened in the original view, where you copied the URL from https://github.com/owncloud/web/issues/6045
    - [ ] default actions
       - [ ] left-click on the `.odt` file
       - [ ] the `.odt` file is opened in Collabora
       - [ ] left-click on the `.docx` file
       - [ ] the `.docx` file is opened in OnlyOffice
       - [ ] ~left-click on the `.md` file~
       - [ ] ~the `.md` file is opened in CodiMD~
       - [ ] upload a `.jpg` file
       - [ ] left-click on the `.jpg` file
       - [ ] the `.jpg` file is opened in the MediaViewer
    - [ ] public links https://github.com/owncloud/ocis/issues/2865
       - [ ] Create a new folder "documents"
       - [ ] Upload ~Create~ a new "collaborative.odt" office file in the folder
       - [ ] Upload ~Create~ a new "collaborative.docx" office file in the folder
       - [ ] Upload ~Create~ a new "collaborative.md" file in the folder
       - [ ] share the folder "documents" with a public link (viewer role, no password, no expiration)
         - [ ] open the public link in an incognito tab
         - [ ] open the `.odt` file in Collabora
         - [ ] The `.odt` file is opened in Collabora in view only mode
         - [ ] open the `.docx` file in OnlyOffice
         - [ ] The `.docx` file is opened in OnlyOffice in view only mode
         - [ ] ~open the `.md` file in CodiMD~
         - [ ] ~The `.md` file is opened in CodiMD in view only mode~
         - [ ] ~copy the URL of the open file view in CodiMD~
         - [ ] ~close the incognito window (clear session)~
         - [ ] ~open the URL in a new incognito window~
         - [ ] ~The `.md` file is opened in CodiMD in view only mode~
       - [ ] share the folder "documents" with a public link (editor role, no password, no expiration)
         - [ ] open the public link in an incognito tab
         - [ ] open the `.odt` file in Collabora
         - [ ] The `.odt` file is opened in Collabora in edit mode and edits can be saved 
         - [ ] open the `.docx` file in OnlyOffice
         - [ ] The `.docx` file is opened in OnlyOffice in edit mode and edits can be saved
         - [ ] ~open the `.md` file in CodiMD~
         - [ ] ~The `.md` file is opened in CodiMD in edit mode and edits can be saved~
         - [ ] ~copy the URL of the open file view in CodiMD~
         - [ ] ~close the incognito window (clear session)~
         - [ ] ~open the URL in a new incognito window~
         - [ ] ~The `.md` file is opened in CodiMD in edit mode and edits can be saved~
       - [ ] share the folder "documents" with a public link (viewer role, with password, no expiration)
         - [ ] open the public link in an incognito tab
         - [ ] enter public share password
         - [ ] ~open the `.odt` file in Collabora~ 
         - [ ] ~The `.odt` file is opened in Collabora in view only mode~
         - [ ] ~open the `.docx` file in OnlyOffice~
         - [ ] ~The `.docx` file is opened in OnlyOffice in view only mode~
         - [ ] ~open the `.md` file in CodiMD~
         - [ ] ~The `.md` file is opened in CodiMD in view only mode~
         - [ ] ~copy the URL of the open file view in CodiMD~
         - [ ] ~close the incognito window (clear session)~
         - [ ] ~open the URL in a new incognito window~
         - [ ] ~The `.md` file is opened in CodiMD in view only mode~
         - [ ] ~copy the URL of the open file view in CodiMD~
         - [ ] ~close the incognito window (clear session)~
         - [ ] ~open the URL in a new incognito window~
         - [ ] ~enter public share password~
         - [ ] ~The `.md` file is opened in CodiMD in view edit mode~
  - [ ] Create a new folder "documents"
    - [ ] Share the folder "documents" with Marie with editor permissions
    - [ ] Upload ~Create~ a new "collaborative.odt" office file in the folder
    - [ ] Upload ~Create~ a new "collaborative.docx" office file in the folder
    - [ ] Upload ~Create~ a new "collaborative.md" file in the folder
    - [ ] open "collaborative.odt" with Collabora and edit some text
    - [ ] open "collaborative.docx" with OnlyOffice and edit some text
    - [ ] open "collaborative.md" with CodiMD and edit some text
- [ ] Login as Marie in a different browser / incognito window
   - [ ] accept "documents" share from Einstein
   - [ ] navigate to "documents" share and open "collaborative.odt" with Collabora
      - [ ] see that Einstein is already editing it and see its cursor and name
      - [ ] changes will be shared between both users' editing sessions
   - [ ] navigate to "documents" share and open "collaborative.docx" with OnlyOffice
      - [ ] see that Einstein is already editing it and see its cursor and name
      - [ ] changes will be shared between both users' editing sessions
   - [ ] ~navigate to "documents" share and open "collaborative.md" with CodiMD~
      - [ ] see that Einstein is already editing it and see its cursor and name
      - [ ] changes will be shared between both users' editing sessions

**Comment by ScharfViktor** [comment]
## Smoke test. branch v1.19.0-rc1

### Case 1: admin share folder(with file) to marie:

Admin:
- [x] upload big file 10gb 
- [x] upload folder with 803 small images. 
- [x] Check pagination, count items per page. - 100 itmes
- [x] upload folder(drag folder) "folder_to_share" with file.pdf
- [x] share folder "folder_to_share" to marie with edit right

Marie:
- [x] accept "folder_to_share"
- [x] rename "folder_to_share"  
- [x] upload new file "file.txt" to "folder_to_share" (admin see new file)
- [x] open pdf file
- [x] rename file.pdf (use rigth click) (admin see that file changed name)

Admin:
- [x] add new file.jpeg to "folder_to_share" (marie can see without accepting)
- [x] move file.pdf to "/" (marie can not see file.pdf)
- [x] add new "file.txt" create new version. (marie can see new version)

Marie:
- [ ] 🚫 can download both versions (!error 501)
- [x] restore old version

Admin:
- [x] change share "folder_to_share" from "edit" to "viewer" (marie cannot rename/move/delete/download file in folder and cannot create new document in the folder)

Marie:
- [x] decline folder (removed from shares folder/removed folder Shares if user hasn't any accepted share)

Admin:
- [x] delete folder "folder_to_share" (removed from shared with me)

## Case 2: admin share file to marie:

Admin:
- [x] upload file.jpeg
- [x] share file.jpeg to marie with rigth viewer (use main menu. find marie by email marie@example.org)

Marie:
- [x] accept file (marie can open/download/copy file but cannot delete/move/rename)
- [x] copy file to "/"
- [x] open file in Mediaviewer
- [x] download file

Admin:
- [x] change share "file.jpeg" from "viewer" to "edit"(marie can open/download/copy/rename file)

Marie:
- [x] rename file (🚫admin don't see)

Admin:
- [x] unshare "file.jpeg" (marie cannot see "file.jpeg" in Shares/Shared for me but see the copied file)

## Case 3: admin create public links to folder

Admin:
- [x] create folder "for upload"
- [x] add link with name "to_upload" with role "Uploader" with pass and expiration date
- [x] open link (can only upload)
log when you open link:
```
2022-03-29T13:29:11+02:00 ERR user not found in context pkg=rgrpc service=storage traceid=00000000000000000000000000000000
2022-03-29T13:29:11+02:00 ERR unary code=Internal end="29/Mar/2022:13:29:11 +0200" from=tcp://127.0.0.1:54769 pkg=rgrpc service=storage start="29/Mar/2022:13:29:11 +0200" time_ns=2415125 traceid=00000000000000000000000000000000 uri=/cs3.gateway.v1beta1.GatewayAPI/CreateHome user-agent=grpc-go/1.45.0
2022-03-29T13:29:11+02:00 ERR error calling CreateHome error="rpc error: code = Internal desc = user not found in context" service=proxy
2022-03-29T13:29:21+02:00 ERR unary code=PermissionDenied end="29/Mar/2022:13:29:21 +0200" from=tcp://127.0.0.1:59970 pkg=rgrpc service=storage start="29/Mar/2022:13:29:21 +0200" time_ns=31667 traceid=00000000000000000000000000000000 uri=/cs3.sharing.collaboration.v1beta1.CollaborationAPI/ListReceivedShares user-agent=grpc-go/1.45.0
```
- [x] upload file (admin can see new file)
- [x] refresh page(page is empty)
- [x] change share "for upload" from "Uploader" to "edit" Bug: https://github.com/owncloud/web/issues/6429
- [x] admin add new file to "for upload"
- [x] refresh link (file exist)
- [x] admin change pass (refresh link has to type new pass)

## Case 4: admin create link to file

Admin:
- [x] create file png
- [x] add link with main menu
- [x] open link(can open, download, see) in the incognito tab
- [x] change link, add pass
- [x] refresh page (input pass)
- [x] admin deletes file, but in public link file exist.
- [x] delete link
- [x] refresh page (resource not found)
- [x] delete file
- [x] restore
- [x] delete
- [x] Empty trash

## Case 6: 

Remarks:

**Comment by micbar** [comment]
Thanks everybody!

🚀
