### ISSUE TITLE
[Epic] Backport experimental branches into master

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis#5184]
# Description

## Goal

- Features from reva `experimental` need to be ported to `edge`
- Features from ocis `experimental` need to be ported to `master`
- Features from web `experimental` need to be ported to `master`
- Features from owncloud-sdk `experimental` needs to be ported to `master`
- The antivirus service needs to be productized

## Features

- [ ] Async Upload
- [x] Full Text Search
- [x] Tags
- [ ] Antivirus
- [ ] Quota Handling options
- [ ] (Activity)

## What means productizing

- [ ] Test Coverage
- [ ] Translations
- [ ] Documentation
- [ ] Get rid `shortcuts` (Code-wise, Architecture, API)

##  Async Upload Productizing

- Can all clients handle all possible `425`?
- BIG question: What to do with WOPI? -> Wopi has no async
  - 1 Download request in the beginning
  - 2 Regular Upload requests (every 5 mins)
  - 3 WOPI has a manual lock on the file and assumes atomicity
  - question: can we disable async for certain requests?
- Question polling / no polling / webhooks
- Documentation
- Is there a requirement that Generic Webdav Clients work (Aka Windows mount, Cyberduck)?
- Test pipeline needs adaptation

@kobergj for backend and @kulmann 

### Linked PRs / Issues

- [x] https://github.com/owncloud/owncloud-sdk/pull/1188
- [x] https://github.com/owncloud/web/pull/8146 (= feature-set of async upload handling as seen in Teststellung)
- [ ] https://github.com/owncloud/web/pull/8069 (= handling of async uploads in all apps + file actions, out of scope for `backport`, but needed for productizing)
- [x] https://github.com/cs3org/reva/pull/3531
- [x] https://github.com/owncloud/ocis/pull/5207
- [x] https://github.com/cs3org/reva/pull/3556
- [x] https://github.com/owncloud/ocis/pull/5244 

## Full Text Search

- Changes from `master` needs to be forward ported
- DEV env needs to be added with apache tika
- Cleanup, do not index when not needed.

@C0rby @fschade 
### Linked PRs / Issues

- [x] https://github.com/owncloud/ocis/pull/5221

## Tags

- Currently implemented as WebDAV properties
- Tags management API -> MS Graph beta spec -> needs understanding and decision @micbar @kulmann @JanAckermann 
- Depends on metadata Store refactoring -> see reva PR
- List of existing tags comes from search index

@JanAckermann @lookacat @kobergj @fschade @JammingBen 
### Linked PRs / Issues

- [x] https://github.com/owncloud/owncloud-sdk/pull/1191
- [x] https://github.com/owncloud/web/pull/8067
- [x] https://github.com/owncloud/ocis/pull/5227
- [x] https://github.com/owncloud/libre-graph-api/pull/62
- [x] https://github.com/owncloud/web/pull/8132
- [ ] https://github.com/owncloud/web/pull/8157
- [x] https://github.com/owncloud/web/issues/8149

## Antivirus

- Continue with closed sources?
- Pipeline
- Tests
- On demand scan in context menu
- Capability for the WebUI action
- Cleanup boiler plate code

## Quota Handling options

- Not yet actionable
- Needs deeper understanding of the requirements @tbsbdr 

## Activity

- Not yet actionable
- Needs concept and understanding of the requirements @tbsbdr
