### ISSUE TITLE
Missing ToDo list available in owncloud.dev when creating a new service

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#5710]
When a new service gets programmed, we do not have a checklist that needs to be processed that the service created is complete. Such a list should be published on `owncloud.dev`. Without claim of completeness or correct sort order, this is:

- [ ] Provide a readme.md for that service
- [ ] If a new CLI command(s) is introduced, that command must be described in the readme.
- [ ] Add the service to the makefile in the ocis repo root
- [ ] Make the service startable for binary and individual startup
- [ ] Make the service appear in `owncloud.dev`
(needs a description what needs to be added so it appears automatically)
- [ ] If there is no extra description, make the readme the description text for that service in owncloud.dev
- [ ] Inform doc team in an _early stage_ to review the readme AND the environment variables created.
(the description must reflect the behaviour AND usually has a positive code quality impact)
- [ ] Create proper description strings for envvars - see other services for examples, especially when it comes to multiple values
(base description, set of available values, description of each value)
- [ ] When suggestable commits are created for text changes and you agree, collect them to a batch and commit them. Do not forget to rebase locally to avoid overwriting the changes made.
- [ ] If new envvars are introduced which serve the same purpose but in multiple services, an additional envvar must be added at the beginning of the list starting with `OCIS_` (global envvar).
- [ ] ...

@micbar @wkloucek @butonic @kobergj

**Comment by mmattel** [comment]
@micbar pls add how to do translations if the service requires this
