### ISSUE TITLE
API tests for antivirus

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#6255]
write some API tests for the antivirus, inspiration can be taken from https://github.com/owncloud/files_antivirus/tree/master/tests/acceptance

documentation https://doc.owncloud.com/ocis/next/deployment/services/s-list/antivirus.html

**Comment by SwikritiT** [comment]
The initial setup of the antivirus is done by this PR: https://github.com/owncloud/ocis/pull/6405

## todo
- [ ] Add the antivirus related setup in docker-compose and update the docs
- [ ] Add more test coverage inspiration can be taken from https://github.com/owncloud/files_antivirus/tree/master/tests/acceptance
  - [ ] add for project spaces
  - [ ] public link sharing
  - [ ] user/group sharing
- [ ] add tests for different values of `ANTIVIRUS_INFECTED_FILE_HANDLING` (default ie delete)
     - [ ] delete (some cases are covered for this)
     - [ ] abort
     - [ ] continue

**Comment by SwikritiT** [comment]
Add coverage for issue : https://github.com/owncloud/enterprise/issues/5709

### Steps to reproduce
1. create file `test.txt` 
2. create some version of file
3. try to upload with replacing a viral file (`echo 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' > test.txt`)
4. try to restore latest version of file

Actual: 
no latest version

### Expected behaviour
user can restore last version of file

**Comment by SwikritiT** [comment]
Add tests for this fixed issue: https://github.com/owncloud/enterprise/issues/5708

### Steps to reproduce
1. create public link to the folder (uploader role)
2. open link and try to upload a zip file with viral file (`echo 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' > clamav-testfile.txt`) -> compress to zip

### Actual: 
500 error

### Expected
201 - file gets uploaded

**Comment by SwikritiT** [comment]
Add tests to cover this fixed issue: https://github.com/owncloud/enterprise/issues/5706

### Steps to reproduce
1. Set the system language to language other than english say `german`
2. create virus file (`echo 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' > clamav-testfile.txt`)
3. try to upload and wait notification

### Actual behaviour
the notification is not translated

### Expected behaviour
the notification is transtaled

**Comment by SwikritiT** [comment]
For the `abort` option of `ANTIVIRUS_INFECTED_FILE_HANDLING` the admin user can get the aborted infected file manually and delete them through cli command as mentioned in this docs https://doc.owncloud.com/ocis/next/deployment/services/s-list/storage-users.html#manage-unfinished-uploads
This information cannot be det through api. so, API tests cannot be added for `ANTIVIRUS_INFECTED_FILE_HANDLING=abort`

**Comment by SwikritiT** [comment]
Blocked until any response in https://github.com/owncloud/ocis/issues/6494

**Comment by ScharfViktor** [comment]
@SwikritiT yesterday I tested the antivirus and checked our api test coverage. I did not find anything new. I think the antivirus coverage is sufficient and we can close this ticket

**Comment by SwikritiT** [comment]
Upon talking with @ScharfViktor, these are some of the test that we can cover
1. Scenario: try to overwrite a file with the virus content in a public link share
2. Scenario: try to overwrite a file with the virus content in user share
3. Scenario: try to overwrite a file with the virus content in group share
4. Scenario: try to overwrite a file with virus content in project space share
5. Scenario: try to overwrite the `.space/readme.md` file

**Comment by SwikritiT** [comment]
All the PR's related to this issue have been merged and backported. Closing this issue as done
