### ISSUE TITLE
ApiTest. next iteration

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6606]
- [x] full search api test (tag, content)  @nabim777 
	- [x] need tika first 
	- [x] search files by tag https://github.com/owncloud/ocis/pull/6641
	- [x] search folder by tag  https://github.com/owncloud/ocis/pull/6725
	- [x] search by tag another user https://github.com/owncloud/ocis/pull/6653
	- [x] search by tag accepted share https://github.com/owncloud/ocis/pull/6659
	- [x] search by deleted tag https://github.com/owncloud/ocis/pull/6660
	- [x] delete resource with tag -> restore resource. TAg exist? search by tag https://github.com/owncloud/ocis/pull/6661
	- [x] search by content https://github.com/owncloud/ocis/pull/6678
	- [x] search by content another user https://github.com/owncloud/ocis/pull/6698
	- [x] search by deleted file using content https://github.com/owncloud/ocis/pull/6707
	- [x] delete resource with content -> restore resource. content exist? search by content https://github.com/owncloud/ocis/pull/6709
	- [x] search version restored files using content  https://github.com/owncloud/ocis/pull/6970
	- [x] search by tag another user (for spaces dav path version ) https://github.com/owncloud/ocis/issues/6669 https://github.com/owncloud/ocis/pull/6853
	- [x] search by tag accepted share (for spaces dav path version ) https://github.com/owncloud/ocis/issues/6669 https://github.com/owncloud/ocis/pull/6853
	- [x]  search files by tag in Project space https://github.com/owncloud/ocis/pull/6853
	- [x]  search folder by tag in Project space https://github.com/owncloud/ocis/pull/6968
	- [x] search by content another user(for spaces dav path version ) https://github.com/owncloud/ocis/issues/6669 https://github.com/owncloud/ocis/pull/6970
	- [x] search version restored files by tag https://github.com/owncloud/ocis/pull/6974
	- [x] search project spaces file by content https://github.com/owncloud/ocis/pull/6987
	- [x] search project spaces file by sharee using tag https://github.com/owncloud/ocis/pull/7036
	- [x] search project spaces file by sharee using content https://github.com/owncloud/ocis/pull/7039
	- [x] ~~search by several tag~~ (feature not implemented yet needs feature request)
- [x] search highlight https://github.com/owncloud/ocis/issues/6426
	- [x] files of different formats in which content extraction is available @SwikritiT  https://github.com/owncloud/ocis/pull/7236
	- [x] ~~different search content: text, numbers, emails, links ...~~ impossible to implement tests due  #6674 
- [x] search in the current folder. location filter @KarunAtreya 
	- [x] personal space https://github.com/owncloud/ocis/pull/6949
	- [x] project space https://github.com/owncloud/ocis/pull/6972
	- [x] shares jail https://github.com/owncloud/ocis/pull/6982
- [x] ENV-> `FRONTEND_ENABLE_RESHARING=false`  @KarunAtreya https://github.com/owncloud/ocis/pull/6665
	- [x] Check that user (perm 15 and 1) https://github.com/owncloud/ocis/pull/6665
	- [x] share with perm 31 via api -> get permission 15 (in response) https://github.com/owncloud/ocis/pull/6665
	- [x] share with perm 17 via api -> get permission 1 (in response) https://github.com/owncloud/ocis/pull/6665

https://doc.owncloud.com/ocis/next/deployment/services/s-list/graph.html @ScharfViktor 
- [x] ENV -> `GRAPH_ASSIGN_DEFAULT_USER_ROLE` https://github.com/owncloud/ocis/pull/6662
- [x] ENV -> `GRAPH_USERNAME_MATCH` https://github.com/owncloud/ocis/pull/6662

- [x] mail notification: @nirajacharya2
    - [x] mail about sharing space to group (all members should get email except sharer user) https://github.com/owncloud/ocis/pull/6633 
	- [x] mail about deleting access to space https://github.com/owncloud/ocis/pull/6657
	- [x] translation mail (share to group where users use different languages) https://github.com/owncloud/ocis/pull/6655 https://github.com/owncloud/ocis/issues/6656
	- [x] ~~mail about deleting access to share~~ no notification (needs a feature request see : https://github.com/owncloud/ocis/issues/6636#issuecomment-1635934281)
	- [x] ~~change role for shared file/folder~~ no notification (needs a feature request see : https://github.com/owncloud/ocis/issues/6637#issuecomment-1707974581)
	- [x] ~~change role for shared spaces~~ no notification (needs a feature request see : https://github.com/owncloud/ocis/issues/6649#issuecomment-1707919956)

- [x] version of shared file: @S-Panta 
 	- [x] recipient-editor cannot see version: [apiSpacesShares/changingFilesShare.feature](https://github.com/owncloud/ocis/blob/2305e08024e57995243b39aeba94e4ea34c01793/tests/acceptance/features/apiSpacesShares/changingFilesShare.feature#L33-L58)
 	- [x] check different roles.https://github.com/owncloud/ocis/pull/6638

- [x] download space @Salipa-Gurung 
	- [x] check archive content https://github.com/owncloud/ocis/pull/6683
	- https://github.com/owncloud/ocis/pull/6854

- [x] increase response checking POST `apps/files_sharing/api/v1/shares ` @ScharfViktor  https://github.com/owncloud/ocis/pull/6627
	- [x] related space_id
	- [x] `uid_file_owner` for personal space -> `user`, for project space -> `spaceId`  https://github.com/owncloud/ocis/pull/6590/commits/b108482649498acefe0b2b7379a403df09816406
  ```
  Then the fields of the last response to user "Alice" should include
      | item_type              | file             |
      | mimetype               | text/plain       |
      | file_target            | /file.txt        |
      | path                   | /folder/file.txt |
      | permissions            | 1                |
      | share_type             | public_link      |
      | displayname_file_owner |                  |
      | displayname_owner      | %displayname%    |
      | uid_file_owner         | %username%       | - user for personal space. spaceId for project space 
      | uid_owner              | %username%       |
  ```

cc @individual-it

**Comment by SwikritiT** [comment]
This PR https://github.com/owncloud/ocis/pull/6880 accidentally closed this.

**Comment by amrita-shrestha** [comment]
have to work on this issue after issue resolve and feature implemented

**Comment by SwikritiT** [comment]
All the PR's have been merged related to this issue so closing this issue
