### ISSUE TITLE
create WebDAV API tests for accessing files by fileID

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#6737]
It is possible to do WebDAV operations using only the fileID. That file can be located in any subfolder, the folder name does not need to be known:
e.g.:
`curl -uadmin:admin -k 'https://localhost:9200/remote.php/dav/spaces/<fileId>' -XPROPFIND`

`curl -uadmin:admin -k 'https://localhost:9200/remote.php/dav/spaces/33c9baa8-450f-4873-a049-7beb8227face$136ffc9b-d317-4219-a0c3-084d5e070c60!0b8eff1a-8401-4bda-a7e7-8333e44e4ded' -XMOVE -H 'Destination: https://localhost:9200/remote.php/dav/spaces/33c9baa8-450f-4873-a049-7beb8227face%24136ffc9b-d317-4219-a0c3-084d5e070c60/Neuer%20Ordner/Artur.txt'`

I don't think we have tests for that, but we should.
- [x] read a file https://github.com/owncloud/ocis/pull/6958 
- [x] update a file https://github.com/owncloud/ocis/pull/6990 
- [ ] rename a file/folder @amrita-shrestha  https://github.com/owncloud/ocis/issues/6981
- [ ] move a file/folder @amrita-shrestha  
     - https://github.com/owncloud/ocis/issues/6983
     - https://github.com/owncloud/ocis/issues/3882
       -  using MOVE
            - https://github.com/owncloud/ocis/issues/1976
            - https://github.com/owncloud/ocis/issues/2442
            - https://github.com/owncloud/ocis/issues/777
       -  using COPY 
           - https://github.com/owncloud/ocis/issues/1977
           - https://github.com/owncloud/ocis/issues/6999
           - https://github.com/owncloud/ocis/issues/4393
- [ ] delete file/folders (known issue: https://github.com/owncloud/ocis/issues/6736)

try that all inside of subfolders & different spaces
try that all with fileIds of other users
try that all with fileId of shared files / folders
try that all with and without `remote.php` in the Destination URL, this seems to make a difference see: https://github.com/owncloud/ocis/issues/6739

**Comment by amrita-shrestha** [comment]
@individual-it using `fileid` we can't rename file in new and old dav-path-version

**Comment by individual-it** [comment]
@amrita-shrestha yes that is true, these tests should only be written for the spaces endpoint

**Comment by SagarGi** [comment]
## TODO to add tests:

#### Inside Personal Space
- [ ] Add copy test with `file-id` (including sub-folders)
- [ ] Add Move test with `file-id` (including sub-folders)

#### Inside Project Space
- [ ] Add copy test with `file-id` (including sub-folders inside a space)
- [ ] Add Move test with `file-id` (including sub-folders inside a space)

#### Inside Shared Space
- [ ] Add copy test with `file-id` (including sub-folders inside a space)
- [ ] Add Move test with `file-id` (including sub-folders inside a space)

**Comment by saw-jan** [comment]
Follow up on the issues mentioned in the above description.
CC @SagarGi

**Comment by SagarGi** [comment]
> Follow up on the issues mentioned in the above description. CC @SagarGi

All the issues mentioned in the  `Copy` and `Move/Rename` is possible through the file id and is done in https://github.com/owncloud/ocis/issues/6737#issuecomment-1723176810 which seems possible except deleting `files/folders with file ID`. So may be those issues seems mentioned seems to be different and unrelated to this issue. The Test coverage regarding the webdav operation with `file_id` seems to be covered. So this issue can be closed.

**Comment by SwikritiT** [comment]
> > Follow up on the issues mentioned in the above description. CC @SagarGi
> 
> @saw-jan @SwikritiT All the issues mentioned in the `Copy` and `Move/Rename` is possible through the file id and is done in [#6737 (comment)](https://github.com/owncloud/ocis/issues/6737#issuecomment-1723176810) which seems possible except deleting `files/folders with file ID`. So may be those issues seems mentioned seems to be different and unrelated to this issue. The Test coverage regarding the webdav operation with `file_id` seems to be covered. So this issue can be closed.

Closing this issue as per this comment
