### ISSUE TITLE
[QA][CI] Have tests running with various deployment setup in CI

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#7614]
Currently, we run tests against the ocis server started from a single binary. We want to have a CI setup where we can start multiple instances of a service (as a load balancing) so that we can test against various deployment strategies.

## Tasks
- [x] one ocis & 2 storage user services. try to spin it up in drone-ci (without Kubernetes)
- [x] try to run e2e tests on that setup
- [x] check the logs if both services receive requests
  - https://github.com/owncloud/ocis/pull/10482
- ~[ ] unskip `smoke` e2e test suite (see [comment](https://github.com/owncloud/ocis/pull/10482#discussion_r1846391628))~ fixed with cors config (https://github.com/owncloud/ocis/issues/7614#issuecomment-2485309180)

Taken from:
- https://github.com/owncloud/ocis/issues/7363
- https://confluence.owncloud.com/pages/viewpage.action?pageId=58296733

**Comment by SagarGi** [comment]
@saw-jan This issue needs to be discussed whether to invest time for doing and running such things in drone as it seems to be whole lot of task.

**Comment by saw-jan** [comment]
>- [ ] unskip `smoke` e2e test suite (see [comment](https://github.com/owncloud/ocis/pull/10482#discussion_r1846391628))

https://github.com/owncloud/ocis/pull/10482#discussion_r1846402263
>It's only the problem with drone setup. I can run the upload test and it passes on local docker compose setup (multi-service)

**Comment by saw-jan** [comment]
I can reproduce the large upload failure with a docker-compose setup.
When running the upload e2e test from the host machine, the test works fine. But if I run the same test from a docker container then the large upload test fails.

**Comment by saw-jan** [comment]
Now I can reproduce it even when running from host machine.

If I use this compose, the large upload test passes. Note `OCIS_URL`
```yaml
ocis:
    image: owncloud/ocis-rolling:master
    ports:
      - 9200:9200
    environment:
      OCIS_URL: https://localhost:9200
      ...
```
Run test with:
```bash
BASE_URL_OCIS=localhost:9200 \
HEADLESS=true \
pnpm test:e2e:cucumber tests/e2e/cucumber/features/smoke/uploadResumable.feature
```

But I use do the following then I cannot upload file larger than 9MB
```yaml
ocis:
    image: owncloud/ocis-rolling:master
    ports:
      - 9200:9200
    environment:
      OCIS_URL: https://host.docker.internal:9200
      ...
    extra_hosts:
      - host.docker.internal:host-gateway
```
Run test with:
```bash
BASE_URL_OCIS=host.docker.internal:9200 \
HEADLESS=true \
pnpm test:e2e:cucumber tests/e2e/cucumber/features/smoke/uploadResumable.feature
```

**Comment by saw-jan** [comment]
I see these logs:
```bash
storageusers-2-1  | {"level":"info","service":"storage-users","pkg":"rhttp","traceid":"47503678543d4903986757df053c350c","time":"2024-11-19T10:25:42Z","line":"github.com/cs3org/reva/v2@v2.26.0/internal/http/interceptors/auth/auth.go:195","message":"skipping auth check for: /data/tus/2da25800-d76b-4257-82e4-18b92c086bb9"}
storageusers-2-1  | {"level":"warn","service":"storage-users","pkg":"rhttp","traceid":"47503678543d4903986757df053c350c","time":"2024-11-19T10:25:42Z","line":"github.com/cs3org/reva/v2@v2.26.0/internal/http/interceptors/auth/auth.go:248","message":"core access token not set"}

```

**Comment by saw-jan** [comment]
And using this cors config made the test pass:
```env
OCIS_CORS_ALLOW_ORIGINS: https://host.docker.internal:9200,https://host.docker.internal:9201
```
