### ISSUE TITLE
[QA][Sharing NG] ApiTest: Extend share link coverage for project spaces

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#9046]
## Describe the bug
Under this issue #7968 test coverage for share link of personal and share drive has been covered. 

## TO-DO
- [ ] Create share link for project drive
- [ ] update share link 
- [ ] remove share link
- [ ] Currently, all share link-related tests exist in the same file `apiSharingNg/linkShare.feature`. If needed split them in `createShareLink.feature`, `removeShareLink.feature`, `updateShareLink`and soon.

**Comment by saw-jan** [comment]
@nirajacharya2 @S-Panta
Which endpoint you are using for the test? drives.permissions or drives.root?

**Comment by saw-jan** [comment]
I would recommend to cover the cases for root endpoint first and then same with permissions endpoint.
Because web client uses root for drive sharing

**Comment by saw-jan** [comment]
Waiting for https://github.com/cs3org/reva/pull/4633
