### ISSUE TITLE
Clean up the ocis issue tracker (timebox: 4PD)

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#9261]
# Description
The ocis issue tracker https://github.com/owncloud/ocis/issues has 688 open issues at the time of writing this (689 when I hit `Submit`). We want to clean up old things which are not needed (anymore) or not actionable (at least where we expect that they won't be actionable for a long time) to make the issue tracker more approachable for everyone.

## User Stories

* > As ownCloud folks we want our issue tracker to be clean so that our beloved product seems active and is approachable for everyone.

## Value
Community

## Acceptance Criteria
Timeboxed to 1 day for max. 4 people

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
- Configuration changes
  - [ ] The next branch of the ocis charts is compatible

**Comment by micbar** [comment]
Best approach would be If two people would pair and ask for each ticket

- Is the content of the ticket still valid for the current master branch?
- Is it a bug which needs to be fixed?
- Is it a feature request which will be implemented in the next 6 Months?

If there are no YESses, close it.

**Comment by micbar** [comment]
We are down to 514 as of today. Great progress!

**Comment by kulmann** [comment]
Results for end of sprint 26:
ocis: 512
web: 219

**Comment by kulmann** [comment]
Current state:
ocis: 511
web: 180

**Comment by kobergj** [comment]
Current state:
ocis: 600 (total:3510)
web: 160 (total:3289)
