### ISSUE TITLE
[QA] Test coverage for activities API

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#9543]
**JIRA:** [#OCISDEV-90](https://kiteworks.atlassian.net/browse/OCISDEV-90)
---
## Description
Add tests coverage for activities api https://owncloud.dev/libre-graph-api/#/activities/GetActivities
- GET `/v1beta1/extensions/org.libregraph/activities`

- web is using this api endpoint ( implemented)

### Scenarios:
- check activities on ocm https://github.com/owncloud/ocis/issues/10073

- [x] check activities for events (applicable to files, folders or spaces):
  - [x] Resource (file/folder):
  - https://github.com/owncloud/ocis/issues/9712
    - [x]  Added https://github.com/owncloud/ocis/pull/9678
    - [x] Deleted https://github.com/owncloud/ocis/pull/9705
    - [x] Moved https://github.com/owncloud/ocis/pull/9731
    - [x] activities of destination file and folder https://github.com/owncloud/ocis/issues/9543#issuecomment-2431703972
      - [x] Moved activities https://github.com/owncloud/ocis/pull/10407
      - [x] Copied activities https://github.com/owncloud/ocis/pull/10485
      - [x] copy zero byte file https://github.com/owncloud/ocis/issues/10417
          - https://github.com/owncloud/ocis/pull/11379
    - [x] Renamed https://github.com/owncloud/ocis/pull/9743
    - [x] Edited https://github.com/owncloud/ocis/issues/10001
        - https://github.com/owncloud/ocis/pull/10230
    - ~[ ] download~ https://github.com/owncloud/ocis/issues/10007 [Not available yet]
      - (not available for authenticated download) https://github.com/owncloud/ocis/pull/10162#issue-2547701975
    - ~[ ] Unauthenticated download (public download)~ [Disabled]
        - https://github.com/owncloud/ocis/issues/10007
        - https://github.com/owncloud/ocis/issues/10231
        - https://github.com/owncloud/ocis/pull/10368
    - [x] try to list activities of another user's file https://github.com/owncloud/ocis/issues/9860
        - https://github.com/owncloud/ocis/pull/10132
     - [x] restore deleted file https://github.com/owncloud/ocis/issues/10010 https://github.com/owncloud/ocis/pull/11485
    - [x] activities of a folder
      - [x] basic activities https://github.com/owncloud/ocis/pull/9796
      - [x] folder rename activities https://github.com/owncloud/ocis/issues/10148
                                          https://github.com/owncloud/ocis/issues/10210
                                           - https://github.com/owncloud/ocis/pull/10395
      - [x] check if scenario mentioned in #9536 is covered @anon-pradip
        - :exclamation: Please, state if this has been checked or not
        &rarr; Covered in: https://github.com/owncloud/ocis/pull/10617

  - [x] Resource (file) - activities using file-id
      - [x] move
        - https://github.com/owncloud/ocis/pull/10312
      - [x] move (destination file and folder)
        - https://github.com/owncloud/ocis/pull/10409
      - [x] copy (destination file and folder)
        - https://github.com/owncloud/ocis/pull/10534
      - [x] copy zero byte file(destination file and folder) https://github.com/owncloud/ocis/issues/10417
          - https://github.com/owncloud/ocis/pull/11379
      - [x] rename https://github.com/owncloud/ocis/issues/9744
        - https://github.com/owncloud/ocis/pull/10312
      - [x] edit
        - https://github.com/owncloud/ocis/pull/10312
      - [x] delete https://github.com/owncloud/ocis/issues/10328
          - https://github.com/owncloud/ocis/pull/11382
      - [x] add a file into a folder https://github.com/owncloud/ocis/pull/11397

  - [x] Share: @prashant-gurung899 
    - [x] Created https://github.com/owncloud/ocis/pull/9795
    - [x] Removed https://github.com/owncloud/ocis/pull/9795
    - [x] Sharee actions (add/edit/delete) on the share - check activity by sharer https://github.com/owncloud/ocis/pull/9818
    - [x] Link Created https://github.com/owncloud/ocis/pull/9803
    - [x] Link Removed https://github.com/owncloud/ocis/pull/9803
    - [x] Member Added https://github.com/owncloud/ocis/pull/9824
    - [x] Member Removed https://github.com/owncloud/ocis/pull/9824
    - [x] Public actions (add/edit/delete) on the share - check activity by sharer #9676
         - https://github.com/owncloud/ocis/pull/10201
    - [x] share receiver can not see any activities, similar to versions (https://github.com/owncloud/ocis/issues/9849)
         >if the user who makes the search request doesn't have the permission to see activities, early return with an error 
         - https://github.com/owncloud/ocis/pull/9842 response (403?)
    - [x] update link share https://github.com/owncloud/ocis/issues/10012
        - https://github.com/owncloud/ocis/pull/10160
    - [x] update share https://github.com/owncloud/ocis/pull/10618
        - https://github.com/owncloud/ocis/issues/10011
        - https://github.com/owncloud/ocis/issues/10228 

- [x] Activity filter: @Salipa-Gurung 
  - [x] depth (`depth:-1`) https://github.com/owncloud/ocis/issues/9850
      - https://github.com/owncloud/ocis/pull/10062
  - [x] depth (`depth:1`) - for folder, should not list the activities for files inside that folder https://github.com/owncloud/ocis/pull/9861
  - [x] limit (`limit:2`) https://github.com/owncloud/ocis/pull/9861
  - [x] sort (`asc`| `desc`)
      - https://github.com/owncloud/ocis/pull/10235
  - [x] limit with sort: https://github.com/owncloud/ocis/issues/10150
       - https://github.com/owncloud/ocis/pull/10234
  - [x] limit (`limit:0`, `limit:-1`) https://github.com/owncloud/ocis/issues/9880 https://github.com/owncloud/ocis/pull/11501

- [x] check activity `message` translation to the language other than English (https://github.com/owncloud/ocis/issues/9856) @prashant-gurung899
  - https://github.com/owncloud/ocis/pull/9875
  - https://github.com/owncloud/ocis/pull/9889
 
- [x] Check activity without `itemid` filter https://github.com/owncloud/ocis/issues/10153 https://github.com/owncloud/ocis/pull/11510  
                                           
## Bug Report:

- [ ] check activities for events (applicable to files, folders or spaces):
  - [ ] Resource (file/folder):
    ~- [ ] file version download~ (knowingly disabled in https://github.com/owncloud/ocis/pull/10368) https://github.com/owncloud/ocis/issues/10008

**Comment by saw-jan** [comment]
Bug reports:
- https://github.com/owncloud/ocis/issues/9676

**Comment by Salipa-Gurung** [comment]
Moving it to backlog blocked untill these issues are fixed:
  1. https://github.com/owncloud/ocis/issues/9676
  2. https://github.com/owncloud/ocis/issues/9683
  3. https://github.com/owncloud/ocis/issues/9712
  4. https://github.com/owncloud/ocis/issues/9744
  5. https://github.com/owncloud/ocis/issues/9849
  6. https://github.com/owncloud/ocis/issues/9860
  7. https://github.com/owncloud/ocis/issues/9880
  8. https://github.com/owncloud/ocis/issues/10073

**Comment by saw-jan** [comment]
Scenarios to test for COPY/MOVE actions:

- copy/move file (having some content) inside a folder
  - check activities of that file
  - check activities of the destination folder

- copy/move file (0 byte) inside a folder
  - check activities of that file
  - check activities of the destination folder

**Comment by prashant-gurung899** [comment]
> Scenarios to test for COPY/MOVE actions:
> 
> * copy/move file (having some content) inside a folder
>   
>   * check activities of the destination file

For this particular MOVE scenario, tests are already covered by :
``` feature
Scenario: check move activity
Scenario: check move activity for a file and a folder
```
For other MOVE scenarios, tests are covered in PR: https://github.com/owncloud/ocis/pull/10407 and https://github.com/owncloud/ocis/pull/10409

And I'm currently working on COPY scenarios.

**Comment by prashant-gurung899** [comment]
COPY (without using file-id)

### copy file (having some content) inside a folder

    check activities of the destination file
        > no response for file copy activity
        > only file added activity response
    check activities of the destination folder
        > full response

### copy file (0 byte) inside a folder

    check activities of the destination file
        > blank response --> {"value":[]}
    check activities of the destination folder 
        >  no copy response

### copy file (some content and 0 byte) inside a folder by renaming the destination file

    file with content
    check activities of the destination file 
        > only folder creation response. no copy response
    check activities of the destination folder 
        > full response

    zero byte file
    check activities of the destination file
        > blank response --> {"value":[]}
    check activities of the destination folder ==> only folder creation response. no copy messsage


copy file (some content and 0 byte) into same folder by renaming the destination file

    check activities of the destination file

**Comment by prashant-gurung899** [comment]
I have made a new issue to report a bug related to copying zero byte file:
https://github.com/owncloud/ocis/issues/10417
cc @saw-jan

**Comment by prashant-gurung899** [comment]
@saw-jan Similarly for copying file using file-id, the zero byte file have no response at all. I have already created a bug report for that. See: https://github.com/owncloud/ocis/issues/9543#issuecomment-2437464133. For other suitable cases, i will write tests in next PR ASAP.

 Please go through the following:

COPY (using file-id)

### copy file (having some content) inside a folder

    check activities of the destination file
        > full response
    check activities of the destination folder
        > full response

### copy file (0 byte) inside a folder

    check activities of the destination file
        > blank response --> {"value":[]}
    check activities of the destination folder 
        >  no copy response. only folder creation response.

### copy file (some content and 0 byte) inside a folder by renaming the destination file

    file with content
    check activities of the destination file 
        > only file added response for "renamed.txt". No previous history.
    check activities of the destination folder 
        > full response

    zero byte file
    check activities of the destination file
        > blank response --> {"value":[]}
    check activities of the destination folder
       > only folder creation response. no copy response


### copy file (some content and 0 byte) into same folder by renaming the destination file

    file with content
    check activities of the destination file 
        > only file added response for "renamed.txt". No previous history.
  
    zero byte file
    check activities of the destination file
        > blank response --> {"value":[]}

**Comment by prashant-gurung899** [comment]
> COPY (using file-id)
> 


Test cases for COPY activities using file-id are covered in this PR: https://github.com/owncloud/ocis/pull/10534
For zero byte files, see :https://github.com/owncloud/ocis/issues/9543#issuecomment-2437464133

**Comment by anon-pradip** [comment]
Checked that for the actions like:
`{user} added {resource} to {folder}`,  `{user} moved {resource} to {folder}` and  `{user} renamed {oldResource} to {resource}`, the `folder name` is placed in the destination placeholder; not the `space name`, which aligns with the expected behavior of issue: #9536

**Comment by anon-pradip** [comment]
> check activities for events (applicable to files, folders or spaces):
>
>   Resource (file/folder):
>   - [ ] file version download (knowingly disabled in 
>
> https://github.com/owncloud/ocis/pull/10368)
>
>        https://github.com/owncloud/ocis/issues/10008


The  behavior is not known yet. So moved this to the backlog of QA project board. Since test coverages for all other issues/fixes have been written, closing this issue.
