### ISSUE TITLE
Activity Type Overview

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/ocis#9999]
- [ ] 1. **what is this?** (UploadReady)
- [ ] 2. New File (FileTouched)
- [ ] 3. **what is this?** (ContainerCreated)
- [ ] 4. Deleted (ItemTrashed)
- [ ] 5. Empty Trashbin (ItemPurged)
- [ ] 6. Moved (ItemMoved)
- [ ] 7. Shared (ShareCreated)
- [ ] 8. Remove share (ShareRemoved)
- [ ] 9. Created Link (LinkCreated)
- [ ] 10. Removed Link (LinkRemoved)
- [ ] 11. Added Member (SpaceShared)
- [ ] 12. Removed Member (SpaceUnshared)

[code pointer](https://github.com/owncloud/ocis/blob/b552c83447eb9998624509a6f952fbb3cdd19d16/services/activitylog/pkg/service/service.go#L98)
